### ISSUE TITLE
Files with nothing in common have more chunks

### ISSUE THREAD

**Issue by jay** [pnedev/compare-plugin#119]
Comparing two files with nothing in common is showing blank lines matching which is separating the match/no-match areas into chunks. Try comparing [these files](https://github.com/jsleroy/compare-plugin/files/819752/navbar.has.more.blocks.zip) for example.
Screenshot pnedev/compare-plugin@2e55f818 (committed last week):
![capture4](https://cloud.githubusercontent.com/assets/965580/23591415/0c775074-01be-11e7-83b5-65e214c06222.PNG)
Screenshot pnedev/compare-plugin@51f0a00 (committed today):
![capture3](https://cloud.githubusercontent.com/assets/965580/23591410/08aef244-01be-11e7-9316-fb4affd20558.PNG)

Originally reported at https://github.com/jsleroy/compare-plugin/issues/66#issuecomment-284263881

Pavel says:

> That is also the behavior before the "vector-out-of-bounds" fix but I agree that the older compare results are better. I'll investigate that. Jay, could you please file a new issue for that but in my fork? Thanks.

But for some reason using a build of the plugin from a week ago does not show the behavior, see the comparison screenshots above.

**Comment by pnedev** [comment]
Hello @jay ,

Thanks for filing this issue. I'll have a look at it soon.

BR

**Comment by pnedev** [comment]
Hello @jay ,

It took me a lot of time to address that issue due to the rework I was busy with.
You can get a 'feeling' of the latest changes if you get the latest dev binaries from this issue: https://github.com/pnedev/compare-plugin/issues/122.

The behavior of the new binary regarding your issue is the same but it is not a bug - the compare finds matching blank lines that make the chunks-looking compare result. There is no plugin option yet to ignore empty lines from the compare process.
Thanks for reporting the issues you've found.

BR
