### ISSUE TITLE
Assess Scintilla annotations capability to replace the alignment blank lines

### ISSUE THREAD

**Issue by pnedev** [pnedev/compare-plugin#122]
That is a high priority task as (if at all possible) this would resolve many issues and improve performance a lot.

PS. Thanks to @dail8859 (https://github.com/dail8859) for the great idea.

**Comment by Yaron10** [comment]
Hello Pavel,

That would be a huge improvement.
Thank you so much for trying it. 👍 

I, too, would like to thank @dail8859 for the idea. 👍 

BR

**Comment by pnedev** [comment]
Hello,

Finally the new alignment implementation (using Scintilla annotations) is ready.
I have fixed several other issues in parallel but I expect others will pop-out as the new alignment was a big rework and the approach is completely different. There are still things to be done like NavBar alignment, some user settings clean-up / implementation and moves detection behavior but the latest code state is completely usable and working in general.
It's worth mentioning that undo / redo is no longer lost - it is working properly with the new approach which is a huge improvement.

Here are the links to the latest binary:
- x86: https://ci.appveyor.com/api/buildjobs/2dbw7r339joeq26i/artifacts/ComparePlugin.dll
- x64: https://ci.appveyor.com/api/buildjobs/nd3b07t1g9g81re6/artifacts/ComparePlugin.dll

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Your enormous work and investment are highly appreciated.

It seems that this refactoring has been more complex and demanding than expected.
-- The fruits of your labor have also exceeded my expectations. I'm really impressed. 

Preserving the Undo/Redo list is an important improvement but, obviously, the most significant change is the new alignment implementation; it makes the results much clearer and easier to grasp.

I understand you've also found a workaround to the [Panes width not equal](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3776) issue.
A special 👍 for that.

***

With your permission, a basic question:

Aligning the diffs is implemented brilliantly. Wouldn't it better to align *all* visible lines?
Let's use [these files](https://github.com/pnedev/compare-plugin/files/1399947/TEST.zip) and NPP layout in the following screenshot as an example. 

![default](https://user-images.githubusercontent.com/10229320/31794455-0bfff9fe-b52b-11e7-94dc-5ec8bdfd1de1.png)

Lines 63-68 match and can be displayed in prefsFFbackup.js instead of the gray block.
I suppose you've thought about that.
***

Thank you also for all the other fixes and improvements.

BR

**Comment by pnedev** [comment]
Hello Yaron,

Thank you for the kind words, I'm glad you appreciate the results from the refactoring.

> Lines 63-68 match and can be displayed in prefsFFbackup.js instead of the gray block.
I suppose you've thought about that.

To do this I'll need to align both documents line by line. That will require inserting a lot of annotations which will come at the cost of performance penalty. Aligning only the diffs is a reasonable compromise I think and also doesn't mess the views a lot. Imagine how the document would look if after each line you had a blank annotation. It would appear very 'segmented' which is undesirable.

Thank you for the feedback.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you for the explanation.
Having used the new version a bit more, it's great as it is. 👍 

BR
