### ISSUE TITLE
[Question] Changed: Precise Condition

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#125]
Hello Pavel,

Why are the following lines marked as Changed?

convert Bookmark14.png -define h:format=rgba -depth 8 -size 14x14 Bookmark14.h
Bookmark14.h (rgba).

Only 16 characters in the second line exist in the first one.

Thank you.

BR

**Comment by pnedev** [comment]
Hello Yaron,

Thanks for filing the issue.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you for looking into it.

BR

**Comment by pnedev** [comment]
Hello @Yaron10 ,

I hope you are doing well :)

The precise condition for the 'lines changed' decision in the latest code (issue https://github.com/pnedev/compare-plugin/issues/122) is this:
If more than half of the words of the longer between the two lines match then the line is considered changed. Please have in mind that the longer line above is in terms of words count not in characters. Please note also that the term 'word' here is any character sequence of a certain type that differs from the surrounding character types (for example '_word$:%get'_ has 3 words - '_word_', '_$:%_' and '_get_').

Please write back if you have any questions / suggestions or need more clarification.
Thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

I'm fine. Thank you.
How are you?

Thank you very much for what I suppose has been a mammoth work. It's indeed highly appreciated.
Congratulations!

I'll have to warm up and get myself into a Compare mode and mood. 
It might take me a few days. Please bear with me. :)

Best regards.

**Comment by pnedev** [comment]
Hello Yaron,

I'm fine as well, thanks. And thank you for the kind words.
Take it easy, whenever you have free time and willingness to play with it :)

Best Regards

**Comment by Yaron10** [comment]
Hello Pavel,

I appreciate your kindness.

I'm looking forward to trying the new version.
In the meantime, allow me to express again my sincere gratitude for your work.

Best regards.

**Comment by Yaron10** [comment]
Hello Pavel,

> The precise condition for the 'lines changed' decision...

Great. 👍 
And thank you for the explanation.
***
Comparing [these files](https://github.com/pnedev/compare-plugin/files/1400057/T.zip), an extra line is added in both files (it's still there after Clear).
Should I open a separate issue?

BR

**Comment by pnedev** [comment]
Hello Yaron,

Yes, that is a workaround I needed to make because Scintilla cannot insert annotation lines before the first document line. The blank line in the beginning is inserted but the file is not saved - if you reload the file you'll see it is not there. I know this is confusing.
Removing the blank line after Clear is not that easy because the user might have made changes to the files and saved them (this means the blank line is also saved) and I'll have to save the file again after removing the blank. As you can see the things are getting messy.

I'll think about a way to deal with this but yes, please move the issue in a separate thread.
Don't bother explaining in details - just give link to this discussion.

Thank you for the feedback, much appreciated.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you for the explanation and best of luck. I wish I could help. :)

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Could you please compare [these](https://github.com/pnedev/compare-plugin/files/1831279/English.zip) NPP English.xml files?

![default](https://user-images.githubusercontent.com/10229320/37684227-0195c086-2c98-11e8-94e8-a413e3122b81.png)

Intuitively I thought there shouldn't be any Added/Removed lines in that section but rather Changed lines (the same is true in lines 392-394).
And indeed in v2 those lines are marked as Changed. Several online Compare sites also mark them as Changed. 

The exact percentage can theoretically be configurable. Well, some time in the future. :)
But for the time being it requires some tuning. What do you think?
***
Comparing the English.xml files I came across the minor caret-issue I mentioned in https://github.com/pnedev/compare-plugin/issues/140#issuecomment-374729070. So I'll post it here.

STR:
Set NPP to width="960" height="732".
Compare the English.xml files.
Place the caret in line 391 in englishNew.xml.
Clear Compare.

Result:
Line 391 is not visible. It works as expected in v2.

Thank you very much for your hard work. Highly appreciated.
BR

**Comment by pnedev** [comment]
Hello Yaron,

Ah, I suppose it is a form of regression I have introduced with the implementation of a feature I could describe as "smart changed lines detection".
For illustration of that feature please compare [**these**](https://github.com/pnedev/compare-plugin/files/1832558/cp_test_data.zip) files with CP v2 and with the latest CP dev version.

I'll

**Comment by pnedev** [comment]
Hello Yaron,

Please test again with [**this**](https://ci.appveyor.com/api/buildjobs/cdw06lawp0sr8xuk/artifacts/ComparePlugin.dll) x86 binary and tell me if you still see issues.

The line position problem is still not fixed.

Thank you.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Great work. :+1: 
Thank you very much. Highly appreciated.

Could you please leave this issue open?
I'd like to further test the English.xml and the cp_test_data files.
Tomorrow and Friday I won't be by my PC.

Also, this issue is probably related to the Move discussion and we might want to re-test it.

> I'll also look into the line position restoration after compare clear.

Thanks again.

BR

**Comment by pnedev** [comment]
Hello Yaron,

Sure, no problem.
'See' you soon ;)

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you.
I'll return to this after the Move discussion has been settled.

Should we open a separate issue for the caret-line after Clear?
I think it's related to https://github.com/pnedev/compare-plugin/issues/141. 

BR

**Comment by pnedev** [comment]
Hello Yaron,

OK.

> Should we open a separate issue for the caret-line after Clear?
I think it's related to #141.

Yes, the issues are related (have the same root-cause).
You can open a new issue if you like.
It is currently low priority for me.
Thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

> You can open a new issue if you like.

It's referenced in https://github.com/pnedev/compare-plugin/issues/141. That we'll do.

> It is currently low priority for me.

Move discussion first. :)
Whenever you find the time.

Thank you very much.
BR

**Comment by pnedev** [comment]
Hello Yaron,

OK, thanks.

BR

**Comment by pnedev** [comment]
Hello Yaron,

I see.
Each changed detection approach so far has proved to be appropriate in one case and not so in another.
I'll look into this soon. I have other urgent tasks these days.

Thanks,
BR

**Comment by Yaron10** [comment]
Hello Pavel,

> Each changed detection approach so far has proved to be appropriate in one case and not so in another.

Indeed.

> I'll look into this soon.

Whenever you can.
Thank you. Much appreciated.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Another interesting case in [these files](https://github.com/pnedev/compare-plugin/files/2054102/TEST.Changed.zip): lines 22 and 19 are marked as Added/Removed.

Whenever you find time to look into it and reply.
Thank you.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Continued from https://github.com/pnedev/compare-plugin/issues/85#issuecomment-465350383.

Thank you for the hex files. I understand it better now.

Allow me to share with you the concept as I see it.
If we assume that the two lines are *not related at all*, they should be marked with +/-.
If, however, there might be some relation - it's obviously better to mark them as Changed and highlight the changes.
GitHub only uses +/- but it does highlight the changes. CP is better but it must highlight the changes whenever possible; the "default marks" (and the equivalent to GitHub) should be Changed. 

Practically...
IMO, the lines in the hex files **must** be marked as Changed regardless of any setting.
They are certainly related.

If you agree, the "Character precision" setting might not be necessary: highlight the entire "word" when possible and the character when it's not.

![default](https://user-images.githubusercontent.com/10229320/53053391-e5bd0c00-34a9-11e9-89fe-44f1036cb9de.png)

![default](https://user-images.githubusercontent.com/10229320/53053408-f2d9fb00-34a9-11e9-8b23-cc23d16c8e7e.png)

![default](https://user-images.githubusercontent.com/10229320/53053434-02f1da80-34aa-11e9-8d34-2179a0e32a1a.png)

I also think that the threshold for regarding the lines as related should be lower. 
 
Currently

`// else` vs. `else`
`// {` vs. `{`
`user` vs. `useg`

are marked as Added/Removed. Marking them as Changed would surly be more correct and helpful.

If making the threshold configurable is too much, what do you think about 10%?

Thank you.
BR

**Comment by pnedev** [comment]
Hello Yaron,

> highlight the entire "word" when possible and the character when it's not.

Hm, I'm afraid I'll need some clarifications here.
Highlighting the entire word is always possible - that means "the words are totally different - no similarities between them". If however the character comparison (which is done on the mismatched words IF _Character precision_ setting is ON finds character similarities between the words (the decision is based on characters match percentage) then only the character diffs are highlighted.

_Character precision_ basically means "do one extra level of compare - character compare" on the yet-mismatched words.

> Currently ...

Only
`// {` vs. `{`
shows as _added/removed_ on my side because of the match threshold (it is currently 35% character match). All other examples are correctly marked as _changed_ and highlighted properly.
Perhaps you have mixed the plugin builds? There are a lot of test builds.

> If making the threshold configurable is too much ...

I have made the preparations for it actually, only the UI part is missing (no setting in the Settings window yet).
Speaking of this, What do you think is a good candidate for such setting's name? I couldn't think of anything easily understandable by the user. `Changed threshold percentage` ?

Thank you for all the suggestions, I appreciate that.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

After posting yesterday I realized it was more complex than I'd thought.
Tabula rasa.

Why do we need the extra Changed mark? Isn't it just confusing? Can't CP use only +/- like GitHub (with changes highlighted)?

I think it's justified if Added/Removed means "These lines are not related at all. Don't start looking for changes.".
And Changed means: "These lines are related. The changes are highlighted.".
It's indeed better and helpful to the user.

If you agree, the lines in the hex files can not be marked as Added/Removed. 
They are certainly related (some 90% character match).

How about always marking them as Changed and highlighting (the entire lines or per-character) according to `Highlight changes at character-level`?
(What do you think of the wording?).

I had some other ideas yesterday but using the setting seems to the best solution. :+1: 
***
You're right: `// else` vs. `else` are correctly marked as Changed.
The other two are Added/Removed.

![default](https://user-images.githubusercontent.com/10229320/53122514-70137780-355f-11e9-92f3-307a9e2478f6.png)

> I have made the preparations for it actually
...

This is great! :+1: 
How about `Mark lines as Changed on 10% character match`? (A combo with various pre-defined values replacing the literal `10%`).

What do you think about changing `Color Settings` to `Color and Highlight Settings` and moving the two new settings to that section?
If you agree, just put them anywhere and I'll fine-tune the UI once the dialog is finalized. 

Thanks again for your excellent work.
BR

**Comment by pnedev** [comment]
Hello Yaron,

Thanks for the feedback and all the suggestions.

> It's indeed better and helpful to the user.

I think that too. :+1: 

> If you agree, the lines in the hex files can not be marked as Added/Removed.

If character precision compare is not done they will be marked that way. That's the idea of the `Character Precision Compare` setting.

> How about always marking them as Changed ...

I don't understand that. They cannot be marked that way always. It depends if they are similar or not (based on character matching). Have in mind that Compare does not know (and does not have a way to know) that the compared text is hex string.

`Highlight changes at character-level` sounds OK but is a bit long (which will increase the settings window size). The setting might as well be a radio button in the style of `Set as First to Compare` - `Highlight Changes at` with variants `Word level` and `Character level` but then it will take space in the vertical direction.

> ... The other two are Added/Removed.

Have you enabled `Character Precision Compare`? You should get `user` and `useg` marked as changed with only `r` and `g` highlighted.

> A combo with various pre-defined values replacing the literal `10%` .

Why not simply use control like `Highlight transparency`? I think it's better suited for our needs. Ranges will be from 1 to 99%.

> What do you think about changing `Color Settings` to `Color and Highlight Settings` and moving the two new settings to that section?

Sounds good :+1: 

> If you agree, just put them anywhere and I'll fine-tune the UI once the dialog is finalized.

Special thanks for that, I appreciate it.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

I did not mean hex files vs. other files.
I was referring to the last three lines in the hex files as an example to related/similar-lines.
And those, IMO, can not be marked as Added/Removed regardless of any setting.

Remember that I'm not familiar with the implementation.
If marking related-lines as Changed would require another comparison-level, I think it should be done.
And the setting should only affect the inner-changes highlighting. 

I'd like to make sure I'm being clear this time.
`Notepad` vs. `Notpad` or `Plugin` vs. `Plugins` should always be marked as Changed.

What do you think?

Thank you. I'll write again later.
BR

**Comment by Yaron10** [comment]
Hello again Pavel,

> The setting might as well be a radio button...

I like that. :)

> Why not simply use control like `Highlight transparency`?

As you understand.
With pre-defined values you don't need to check the user's string and and prompt error messages etc.. 

> Have you enabled `Character Precision Compare`? You should get `user` and `useg` marked as changed with only `r` and `g` highlighted.

What's wrong with me?
Perhaps I had in mind the concept that they should always be Changed.

Thank you.
BR

**Comment by pnedev** [comment]
Hi Yaron,

> I was referring to the last three lines in the hex files as an example to related/similar-lines.
> And those, IMO, can not be marked as Added/Removed regardless of any setting.

Why? How would they be marked if you switch of character level highlighting? The whole lines should be highlighted but marked as changed? The user might ask then "What is the similarity between these lines, why am I not shown what portions match?"

> And the setting should only affect the inner-changes highlighting.

Well, if we don't desire inner-changes highlighting then there would be no point in doing extra comparing (on character level). It will simply take the extra time and the results will not be present.

> `Notepad` vs. `Notpad` or `Plugin` vs. `Plugins` should always be marked as Changed.

How exactly would they be highlighted if "Character level highlighting" is switched off?
Again Changed and highlighted at word level?
IMO that will be confusing for the user. If he/she decides he/she needs such information (that the words are similar on character level) he/she will need to know where exactly is the similarity and enable "Character level highlighting" respectively.

Do you agree?
------------------------------------------------------------------------------------------
> I like that. :)

So be it :+1: 

> With pre-defined values you don't need to check the user's string and and prompt error messages etc..

I promise there will be no error messages. If the setting is below/above the possible range I'll automatically take the lower/upper boundary.

Thank you, I appreciate your feedback.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Your questions are all good and I did think about them.

> And those, IMO, can not be marked as Added/Removed regardless of any setting.
...
Why?

Because Added/Removed should mean "These lines are not related at all. Don't start looking for changes.".
Marking `Plugin` vs. `Plugins` with +/- would be misleading and wrong.

> How exactly would they be highlighted if "Character level highlighting" is switched off? 
Again Changed and highlighted at word level?

Indeed.
Yes, the user might wonder where the inner-changes highlights are but they would at least pause and realize the lines are related.

Alternatively, allow me to return to my suggestion from some posts above:
 If the line contains only one "word", highlight at character-level *even if that setting is OFF*. 
(The setting would be something like `Default highlight level` defaulted to `Word` as character-level can be distracting in many cases).

I actually retracted this suggestion because it would be strange: `Plugin` vs. `Plugins` should be highlighted at character-level whereas `Some Plugin` vs. `Some Plugins` would be highlighted at word-level.
But thinking about it again, it may be the preferred solution.

Another option I thought about was a slightly different Changed symbol for `Plugin` vs. `Plugins` but I suppose it would be too much.

None of these solution is ideal but I do believe they are better than marking strongly-related-lines with +/-. 

What do you think?
***
> So be it.

Great.

> I promise there will be no error messages. If the setting is below/above the possible range I'll automatically take the lower/upper boundary.

Excellent. :+1: 

Thank you very much. I appreciate it.
BR

**Comment by Yaron10** [comment]
Hello again Pavel,

The character-match threshold for Changed lines, actually defines Added/Removed as well.
For example: 10% and above - Changed/Related, below - Added/Removed/Not-Related.
So lines considered by the user as related can not be marked as Added/Removed.

Thank you.
Have a nice weekend.

**Comment by pnedev** [comment]
Hello Yaron,

Thank you for the detailed feedback.
I really do appreciate you opinion but I strongly disagree with marking lines as 'Changed' without showing where the changes are.

As I've said before, 'Changed' decision is very tricky and one solution is good and suitable for one case and other - for another. Thus I prefer to give more control to the user. The changed threshold percentage is one such setting and the other would be the highlight level (which is also the compare granularity level).

Let me give some examples to justify my perspective.
There are many different text files with different types of content and the user looks at them differently.
For instance, if compared text files contain hex data the user is interested in the _syntactic_ differences and here the character level compare / highlighting is for sure needed. The user should be aware of that and use character level highlighting.
In the case of regular text (meaningful sentences) the user's point of view is _semantic_. That's why the user is probably not interested in the character similarities between the sentences and would find it confusing if the word highlighting is chosen, two lines contain very different (semantically) sentences and yet, they are marked 'Changed' because they happen to be syntactically similar.
For example `tree` is different from `tee`, `dog` from `fog`, `live` from `five` .... you get it.
Try comparing `i've lived` vs. `give five` with and without "Character precision compare" in the current Settings implementation.
That's why I prefer to leave it to the user to choose if he/she is interested in the semantic or the syntactic differences and don't bother him/her anymore with 'similarities' he/she doesn't care about.

> The character-match threshold for Changed lines, actually defines Added/Removed as well.

That's true. 

> So lines considered by the user as related can not be marked as Added/Removed.

If the threshold and the highlighting is set by the user then he/she actually defines what he/she considers related. Compare plugin just provides the means to do the compare in the desired way. That's why the 'Ignore' options are there as well.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

A great analysis. :+1: I was impressed. 

After first reading it I tended to agree with all of your points.
Analyzing it again, I think that my basic initial conclusion is correct but it's easier for me to understand your approach.

**1)**
> Thus I prefer to give more control to the user.

You're right.
And my suggestion "If the line contains only one "word", highlight at character-level even if that setting is OFF" is wrong.

**2)**
The definition of Changed (and Added/Removed) is not set exclusively by the threshold but rather by the the two settings combined. 

That's good. I still think though that it would be better if +/- meant "Not-Related".

**3)**
> For example `tree` is different from `tee`, `dog` from `fog`, `live` from `five` ..

`Some tree` vs. `Some tee` are marked as Changed. 
In terms of "syntactic/semantic", what's the difference between those and `tree` vs. `tee`.

Think also of `else` vs. `els`. Wouldn't it be clearer if they were marked as Changed?

**4)**
> I strongly disagree with marking lines as 'Changed' without showing where the changes are.

I can certainly understand that. I also thought it would be strange.

**Conclusion.**
Your opinion is obviously more important.
Point **2** makes the concept more "digestible". :)
***
`i've lived` vs. `give five`.
I'm afraid I don't understand that.
Do you mean they should be marked as +/- although the words can be highlighted? Why?

Thank you very much. Much appreciated.
BR

**Comment by pnedev** [comment]
Hello Yaron,

> I still think though that it would be better if +/- meant "Not-Related".

To some extent that's what it means. It means "I cannot find relation between those based on the current compare criterion".

> `Some tree` vs. `Some tee` are marked as Changed.
> In terms of "syntactic/semantic", what's the difference between those and `tree` vs. `tee`?

The difference is that there is another word matching completely - `Some` . If character highlighting is OFF and two sentences have percentage of matching words higher than the given threshold then those will be marked "Changed".

> Think also of `else` vs. `els`. Wouldn't it be clearer if they were marked as Changed?

Not exactly. They do not have context. These are two non-matching words and if you do word highlighting (word compare) they are actually different.

Word vs. character is exactly what it says - this is what is the level of difference you are interested in. Do you care about character differences? If no, in the case of `else` vs. `els` you get +/- marks aligned meaning that the `else` line was replaced by the `els` line.
Another example:
If you compare numbers (some measurement perhaps or scientific data, `1462059152` vs. `1461981451`) it is meaningless that they have some matching digits. There is simply no point in comparing them on character level. But if you have mistakenly entered some code or ID that is pretty long and you want to find where exactly you have made a mistake it is a case like in hex compare - you care exactly about the characters mismatch.

There are a lot of corner cases, exceptions, etc. but there always will be due to the diversity of compared data. I'm trying to find the "most" reasonable and universal solution and give the user the opportunity to fine-tune his/hers particular compare to find exactly what he/she is looking for without distractions. That's what all these user requests are about - Ignore empty lines, Ignore some regular expressions, Ignore case, Hide matches, you name it.

> I'm afraid I don't understand that.
> Do you mean they should be marked as +/- although the words can be highlighted? Why?

This was just an example of the effect character highlighting has. And the compare point of view - syntactic mismatch or some context - semantic mismatch.
Yes, in case of word level compare it should be marked as +/- . There isn't a single word here that matches completely so most probably the whole sentence is replaced. But if you'd like to see character differences then OK - set char level and go on.

Thank you for all the time you invest in compare and for always thinking of a way to make it better.
I appreciate that.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thanks again for the detailed reply. I do appreciate it.
Relative to the Move discussion, it wasn't that long. :)

Excellent work. :+1: 

`i've lived` vs. `give five`.
(Word highlighting).

I misunderstood the threshold rule.
I thought that `ive` was the required character-match for marking the lines as Changed and then the space should be highlighted as inner-match and the *words* as inner-changes.

I now realize that the threshold character-match refers to the final *inner-match*.
Could you please confirm I got it correctly?

BR

**Comment by pnedev** [comment]
Hello Yaron,

Thank you.

> I now realize that the threshold character-match refers to the final _inner-match_.
> Could you please confirm I got it correctly?

To the extent I understand your question - yes.
There is no difference between what is counted for the threshold and finally shown as matching - no separation between 'Changed' decision and highlighting.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you. I appreciate it.

I used CP for a "real-life" compare session and the new improvements are very good.
The "Show Only Diffs" option was particularly useful. :+1: 

During that "session" I thought that "Highlight changes at character-level" might be used quite frequently and placing it in the menu would be more convenient.
What do you think?

BR

**Comment by pnedev** [comment]
Hello Yaron,

Thank you.

> ... and placing it in the menu would be more convenient ...

Honestly I don't know. Both variants are OK for me.
You seem to prefer it in the menu so I'll put it there.

BR

**Comment by pnedev** [comment]
Hello Yaron,

Try this binary (but please erase your ComparePlugin.ini first):
https://ci.appveyor.com/api/buildjobs/etvdvbw4eha93nn0/artifacts/ComparePlugin.dll .

This binary is the same as this one - https://github.com/pnedev/compare-plugin/issues/85#issuecomment-468364317 .

BR

**Comment by Yaron10** [comment]
Hello Pavel,

:+1: 
Thanks for that too. Much appreciated.

BR

**Comment by pnedev** [comment]
Hello Yaron,

[**This**](https://ci.appveyor.com/api/buildjobs/82ggsa461wbavyru/artifacts/ComparePlugin.dll) binary has implemented "Change threshold percentage" setting with several other changes.
You'll have to delete again your ComparePlugin.ini.

If you think there are no more "Changed" issues you can close this thread.
Thank you.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Great job. The Settings dialog design is also very nice. 
:+1: 


Could you please compare [these](https://github.com/pnedev/compare-plugin/files/2921556/TEST.zip) files?
If "Ignore Spaces" is ON, `// else` vs. `else` are marked +/-.

![default](https://user-images.githubusercontent.com/10229320/53674008-b53c5580-3c93-11e9-8f21-cb7242306010.png)

Comparing just the two lines (`// else` vs. `else`) without changing any setting - they are marked as Changed. 

Thank you. I appreciate your hard work.

BR

**Comment by pnedev** [comment]
Hello Yaron,

Thank you.
That looks strange indeed, I'll have a look and write back.
Have a nice weekend.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you for looking into it. I appreciate it.

Have a nice weekend too.

**Comment by pnedev** [comment]
Hello Yaron,

Please try this build:
https://ci.appveyor.com/api/buildjobs/jeatr3cm4nyknpn6/artifacts/ComparePlugin.dll 
(same as in https://github.com/pnedev/compare-plugin/issues/191).

Many thanks.
BR

**Comment by Yaron10** [comment]
Hello Pavel,

:+1: 
Great. Another issue closed. :)

Thank you very much. I do appreciate your hard work.
BR
