### ISSUE TITLE
[Enhancement] Select and Search in Other View

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#144]
Hello Pavel,

An idea for the future. :)

I often want to know if some text (e.g. part of a line) appears in the other file.
Currently you would select some text, open the Incremental Search Bar, switch to the other file and use the Search Bar again.  
I've written a `Select and Search in Other View` [Python Script](https://github.com/pnedev/compare-plugin/files/1412542/Select.and.Search.in.Other.View.zip) and the basic implementation is as follows:

Select some text.
Press `Select and Search in Other View`.

If the selected text exists in the other file, it is highlighted/flashed in dark green.
If it does not exist, it is highlighted/flashed in dark red. 

How about adding this feature to CP?

Thank you.
BR

**Comment by pnedev** [comment]
Hello Yaron,

Though it sounds interesting and useful it is not exactly Compare related feature is it?
It doesn't hurt having that anyway, I'll consider adding it to CP.

That should be accessible even when we are not in compare mode (just having two panes open), right?

Thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

> That should be accessible even when we are not in compare mode (just having two panes open), right?

That's correct.
Still it can be a nice complementary feature to CP.

Thank you for considering it. 
Some time in the future. :)

BR

**Comment by pnedev** [comment]
Hello Yaron,

> Still it can be a nice complementary feature to CP.

I suppose so.
Do you have any idea for the command name?
Thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

I suppose you'd consider `Select and Search in Other View` too long.
Would `Search in Other View` be enough?

Back to the future? :)

Anyway, a short note:
In my script - pressing the left mouse button, the selected text in the *active file* is flashed; pressing the right mouse button, the other file is activated and the text there is flashed (if found).

Thank you very much.
BR

**Comment by pnedev** [comment]
Hello Yaron,

I implemented another compare command that is somewhat linked to the functionality you mention here.
Please have a look at the binary from https://github.com/pnedev/compare-plugin/issues/145 (https://ci.appveyor.com/api/buildjobs/r4a5wsiq3pqu5uia/artifacts/ComparePlugin.dll).
There are two new commands _Find Unique Lines_ and _Find Unique Lines in Selection_.
The idea is to highlight the lines that appear only in one of the files (or in the selections in both files). The 'new' file's unique lines are marked as 'added' and the 'old' file's - as 'deleted' respectively.
This is still in development so the navigation commands do not work as they should yet. The vertical scroll is also irrelevant here and won't be active because the files' diffs are not aligned. That's because the alignment is pointless in that case.
Thank you.

BR

**Comment by pnedev** [comment]
Hello again, Yaron,

For better view and for fixing the compare status info please test with the following x86 binary:
https://ci.appveyor.com/api/buildjobs/fcb312blk4ptxq1p/artifacts/ComparePlugin.dll

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Being able to know which line appears as is in the other file is a useful addition. 👍 
Thank you very much.

**Per line vs. per file info**

In the [Move discussion](https://github.com/pnedev/compare-plugin/issues/113) I've suggested to distinguish between a line Added/Removed *in this location* to a line Added/Removed *in the entire other file*.
(![default](https://user-images.githubusercontent.com/10229320/33143336-408e0e16-cfc2-11e7-848f-f6bdc8b8ef84.png) for a "global added" and ![default](https://user-images.githubusercontent.com/10229320/33143395-6cff1aee-cfc2-11e7-81a7-1cf69ade2bec.png) for a "local added").

If we take it a step further and use different icons for a Changed line (appearing as is somewhere else in the other file) and a Changed-Unique line, we'd get the per-file info in a regular Compare.

The *Find Unique Lines* presentation is different and can still be very useful.
(Regarding the command name: IMO it should start with "Compare" (e.g. *Compare and Mark Unique Lines*). What do you think?).
***
Some basic and not fully baked ideas:

How about a *Special Compare* menu item and the following commands in a sub-menu?
*Compare and Mark Unique Lines*.
*Compare and Mark Changed Lines* (the user might be interested only in those). 
*Compare and Mark Moved Lines*.

And *Hide Other Lines*?

It can actually be implemented in a regular Compare.
*Display Changed-Lines Only* etc.. 

For the future. :)

Thanks again for your great work.
BR

**Comment by pnedev** [comment]
Hello Yaron,

Thank you.

> In the Move discussion I've suggested to distinguish between a line Added/Removed in this location to a line Added/Removed in the entire other file.

I can't recall that, sorry. A lot of time has passed.
It is actually a move detection, is it not?

> Regarding the command name: IMO it should start with "Compare" (e.g. Compare and Mark Unique Lines). What do you think?

_Compare and Mark Unique_ is more explanatory but somewhat misleading.
I intentionally want to separate that from _Compare_ because it is noticeably different - **it does not detect line positions changes**! And line positions change is a very important thing for most file types (sources, contracts, documents, you name it). _Find Unique_ fills the gap when you don't care about positioning changes - you are just checking if _that thing is still in the list / database_. It is kind of a dictionary / settings / werehouse's list compare.

> How about a Special Compare menu item and the following commands in a sub-menu?

I have thought about that, yes (+ _Set First_ and _Clear Compare_). It will be a useful addition (for the 'not-so-near' future :)).

> And Hide Other Lines?

That sounds nice but will open the Pandora's box and we don't want to do that :)

Thank you for the feedback and the suggestions, appreciated as always.

P.S. Do the new command make the current feature request obsolete? It does solve the problem and it resembles compare operation more (as opposed to checking if a certain line is present in the other file which resembles search functionality respectively)?

BR

**Comment by Yaron10** [comment]
Hello Pavel,

> In the Move discussion I've suggested to distinguish between a line Added/Removed in this location to a line Added/Removed in the entire other file.
...
It is actually a move detection, is it not?

Not necessarily. When you're ready to resume the Move discussion. :) 

> Compare and Mark Unique is more explanatory but somewhat misleading...

Thanks for the explanation.

> I have thought about that, yes (+ Set First and Clear Compare). It will be a useful addition (for the 'not-so-near' future :)).
...
That sounds nice but will open the Pandora's box and we don't want to do that :)

👍 

> Do the new command make the current feature request obsolete? It does solve the problem... 

I often want to know if *part* of a line exists in the other file.
I have the script for my personal use. :)
Should I close this issue and reopen it in the 'not-so-near' future?

Thank you very much.
BR

**Comment by Yaron10** [comment]
Hello again Pavel,

I had not realized the new command was meant to be a solution to my request.
Special thanks. Highly appreciated.

It's a great addition regardless. 👍 
 
BR

**Comment by pnedev** [comment]
Hello Yaron,

> When you're ready to resume the Move discussion.

Until then, then :)

> I had not realized the new command was meant to be a solution to my request.

While discussing various details with you I got some impression of your use cases (the 'detect multiple moved' and this request) and I realized that such functionality (Find unique) might be useful to you and other CP users. Besides it is complementary to the Compare operation as such - disregard the lines order and yet check if some are present only in one of the files. Thanks.

> I often want to know if part of a line exists in the other file.
I have the script for my personal use.

That is useful but I don't consider such function a 'compare' one. It is more of a 'search' function and you can easily do that without additional plugin command - either manually, with your python script or with a macro (perhaps). I'm sorry if you expected to have it and you are disappointed.

You can close this thread unless you'd like to discuss more something related to it
Thank you.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thanks again for your kindness. Much appreciated.
I'll close this issue. :)

BR
