### ISSUE TITLE
Keep Undo history after Clear Compare

### ISSUE THREAD

**Issue by trefrog** [pnedev/compare-plugin#161]
After editing during compare, then hitting the clear button, the undo menu item greys out. Would be really great if the undo history could be kept.

**Comment by trefrog** [comment]
didn't see the closed issue... from just 5 days ago. derp. I'm a noob

**Comment by pnedev** [comment]
Hello @trefrog ,

Yes, the undo is fixed in the current development version but it is not officially released yet.
It will be some time soon (I've been telling this to everybody these days but I don't have much time working on CP so it might take longer than I expect).

Till then, you can however use the development binaries. You don't have to compile those.
The latest can be found here: https://ci.appveyor.com/project/pnedev/compare-plugin -
get a Release build for your platform (x86 or x64). Click  on its link and the plugin dll is in the Artifacts section. For instance: https://ci.appveyor.com/api/buildjobs/cj1nchrah6iahpyn/artifacts/ComparePlugin.dll

BR
