### ISSUE TITLE
Color Setting for Text (Dark themes)

### ISSUE THREAD

**Issue by derek-shnosh** [pnedev/compare-plugin#193]
## Issue

When using a dark where the text is white (e.g. Black board), the highlighted text is very difficult to read.

### Example

![image](https://user-images.githubusercontent.com/21090563/53991186-e88d4300-40de-11e9-853a-b39b81acfb40.png)

## Suggestion

Add a *Highlighted Text* color option **Settings > Color Settings** area.

**Comment by Yaron10** [comment]
Hello @derek-shnosh,

You can change the highlight color of Added/Removed lines in `Settings > Color Settings`.

**Comment by derek-shnosh** [comment]
@Yaron10 I am not trying to change the highlight color, I would like to change the _color of the font_ on a highlighted line.

**Comment by pnedev** [comment]
Hello @derek-shnosh ,

I'll consider implementing such setting, thanks.

@Yaron10 , thank you for providing support, I appreciate it.

BR

**Comment by pnedev** [comment]
Hello again @derek-shnosh ,

It is not possible to implement such feature in a reasonable way because the font color is set by the lexer in use. And the lexer often restyles the document which would be overwriting any change in the font I could have applied from Compare. Besides this way if you compare files with certain styling (recognized source files) you won't be loosing the font styling.

So the only option you have is to pick compare mark colors that work well your chosen Notepad++ theme.
Sorry.

BR

**Comment by derek-shnosh** [comment]
@pnedev, completely understandable. Thank you for you work on this project and taking the some time to look into this and provide an update.

**Comment by Yaron10** [comment]
Hello Pavel,

:+1: 

May I ask you to have a look at another NPP behavior which might affect CP?
 (Not related to this issue).

**STR:**
Open [this](https://github.com/pnedev/compare-plugin/files/2946664/langs.model.zip) file.
Paste `<Language name="rebol"` in the incremental search bar.

![default](https://user-images.githubusercontent.com/10229320/54041384-42216a80-41d0-11e9-9d06-59b9e1c9a6db.png)

Switch to another tab.
Switch back to `langs.model.xml`.

**Result:**
 NPP displays the beginning of line 298 and line 301 is not visible.

![default](https://user-images.githubusercontent.com/10229320/54041865-7ba6a580-41d1-11e9-8141-391ed368489f.png)

This may also happen with highlighted compared line.

Thank you very much.
BR

**Comment by pnedev** [comment]
Hello Yaron,

I couldn't reproduce the issue. What is your Notepad++ version? I am on 7.6.3.
Could you also try with LTR settings?
Thank you.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you for trying.

I'm using 7.6.4. I downloaded a fresh portable 7.6.3 and got the same result.
The visibility of line 301 may depend on the window size but NPP jumping to the beginning of a wrapped line is consistent.

BR

**Comment by pnedev** [comment]
Hello Yaron,

Ah, yes, I see it now. My monitor is big enough in horizontal direction thus the problem was masked.
I can confirm that it affects CP as well but I am not sure I can do something about that. When I start working on https://github.com/pnedev/compare-plugin/issues/141 I'll try to figure out a way to circumvent both issues.
Thanks for pointing that out :+1: 

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you for testing and confirming. I appreciate it.

> but I am not sure I can do something about that. When I start working on #141 I'll try to figure out a way to circumvent both issues.

:+1: 
Great.

That was indeed my purpose. I realized that some of the caret/position issues were caused by NPP (well :) )  and wanted to share it with you.

I usually don't think there's a point in opening issues on NPP repo but I'll try.

BR
