### ISSUE TITLE
icon sizes on 4k displays

### ISSUE THREAD

**Issue by i3luefire** [pnedev/compare-plugin#194]
I am using a 4k resolution display. the icons for this plugin are very small on this display compared to the other icons in notepad++.
![image](https://user-images.githubusercontent.com/3527233/54882255-1c2dd400-4e26-11e9-8728-a2aea109d5ab.png)

**Comment by pnedev** [comment]
Thanks for reporting I'll see what I can do.

BR

**Comment by Yaron10** [comment]
Hello Pavel and @i3luefire,

Pavel,

Thank you for that too.

NPP starches its 16x16 icons. DSpellCheck has a separate 32x32 icon but - as far as I can judge by the screenshot - its icon is also slightly starched.
I suppose that adding new 32x32 (and perhaps more) icons to CP would be too much.
What do you think?

BR

**Comment by pnedev** [comment]
Hello Yaron,

I am not quite aware (yet) with icon handling in Notepad++ and in general but I think adding more icons will indeed be too much.
What we need is to re-scale the icons IMO but isn't it better to change all the existing icons to 32x32 so the scaling goes downwards? This way the bigger icons won't be 'rough' and the small ones won't change. I don't know, what do you think? Is it a lot of work on your side?

Thank you, I appreciate your help as always.

BR

**Comment by pnedev** [comment]
Hello again, Yaron,

It appears that we just need to make the icons icons :)
I mean if the resource files are not bitmaps but actual icons the resizing should take place.
How difficult will it be to convert all bitmaps to icons?

Thanks a ton.
BR

**Comment by Yaron10** [comment]
Hello Pavel,

Converting BMP images to [ICO images](https://github.com/pnedev/compare-plugin/files/3010683/res.zip) is easy.

NPP uses 16x16 BMP images (PowerEditor\src\icons) for the standard toolbar.
The larger images in @i3luefire's screenshot are stretched/re-scaled.
`CustomizeToolbar` also states you should use 16x16 BMP images.
`DSpellCheck` Resources contain 16x16 BMP images and also an ICO file with several formats (16x16, 32x32 and more).

> It appears that we just need to make the icons icons

ICO files can contain various image formats and Windows selects the correct one according to the view (e.g. `Details` or `Large Icons` in Windows Explorer).
I'm not sure it would be that simple in NPP's standard toolbar.

Re-scaling can be done with BMP as well as ICO.
(NPP's `ToolBar.cpp` has some instances of `NppParameters::getInstance()->_dpiManager` which are probably relevant).
If you prefer not to re-scale but have actual different formats, you'd have to use ICO and I'd be glad to make them.

Two points to consider:
1. It would increase the size of the DLL.
2. Some users might request 24x24 and 48x48 formats as well.

Since there's already a `Compare.ico` file in CP's resources, I've changed the toolbar icon name to `CompareCommand.ico`.
This file contains two formats (16x16 and 32x32) if you decide to test it; the 32x32 image is that of `File mp3.ico`. 

> What we need is to re-scale the icons IMO but isn't it better to change all the existing icons to 32x32 so the scaling goes downwards? This way the bigger icons won't be 'rough' and the small ones won't change.

A re-scaled 16x16 image (from 32x32) would look as bad as a re-scaled 32x32 image (from 16x16).
So I think it would be better to use proper 16x16 images for the vast majority of NPP users.

**Summery:** :)

Adding actual different formats (possibly 24x24, 32x32 and 48x48) to CP (10 toolbar icons) seems too much.
If you agree, there's no point in testing the ICO images as re-scaling can be done with BMP.
If you think it's worth it, I'd make the needed ICO files.

Thank you. Much appreciated.
BR

**Comment by pnedev** [comment]
Hello Yaron,

Thank you very much for the quick response and the info.

> A re-scaled 16x16 image (from 32x32) would look as bad as a re-scaled 32x32 image (from 16x16).

Are you sure about that? I have doubts but I'll trust your judgement on this :+1: 

I fully agree with your summary and I hope I didn't waste your time in vein creating the ico files you sent.

The bitmaps re-scaling is implemented here:
https://ci.appveyor.com/api/buildjobs/ke6fi16xspc1w4xr/artifacts/ComparePlugin.dll .

@i3luefire ,
The re-scaled toolbar icons will be available in the next release, thank you for reporting.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

> Are you sure about that? I have doubts

Highly respecting your opinion, I'm trying to understand why you doubt that.
The *quality* of the images is **32bpp** (not 16). The discussion here is about *size*.
Why would re-scaling a larger image be better? - From my experience in image-editors it's often worse.

> I hope I didn't waste your time in vein creating the ico files you sent.

No problem at all. The conversion is really easy.

Thank you for the quick fix. :+1: 
Could you please post a screenshot with the stretched larger images?
My monitor is not a good indication.

BR

**Comment by pnedev** [comment]
Hello Yaron,

I was not talking about the bpp (color) but the image resolution (size).

If the image is 16x16 pixels it needs to be resized upwards to fit in 32x32 area which requires some interpolation algorithm to generate the missing data.
If the image is 32x32 pixels and it needs to fit in area 16x16 then the image needs to be scaled downwards (decimated) which is done by discarding some of the existing data.
If you have a photo that doesn't fit on your monitor and you up-scale it it will look worse compared to a photo which is bigger than the monitor and you down-scale it.
That's why I doubt that down-scaled bigger (in resolution) images will look equally bad as up-scaled ones.

Up-scaled images tend to look either "rough" or "blurred" depending on the missing pixels reconstruction method (the interpolation).

Here is a screenshot of the up-scaled toolbar:

![resized_toolbar](https://user-images.githubusercontent.com/6064913/55142270-e8fc8500-5144-11e9-8f28-2da68ecb34f3.png)

It looks pretty nice IMO.

Thanks.
BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you for clarifying.

> If the image is 32x32 pixels and it needs to fit in area 16x16 then the image needs to be scaled downwards (decimated) which is done by discarding some of the existing data.

:+1: 
And that's why in some case it would look worse than "up-scaling".

> If you have a photo that doesn't fit on your monitor and you up-scale it it will look worse compared to a photo which is bigger than the monitor and you down-scale it.

Yes, this may be the case - depending on the image.

Do you agree that the majority of NPP users use the toolbar un-scaled? - For them *proper* 16x16 images are certainly better.
Also, this is the size NPP provides.

If you would like to test 32x32, I'll make one at first and the rest later if you think the re-scaled 16x16 is OK.
If for your personal use 32x32 images look better, I'd be really glad to make all of them.

Thank you for the screenshot. It actually looks better than I'd expected.

BR

**Comment by pnedev** [comment]
Hello Yaron,

Thank you for the quick reply.
Please don't bother creating 32x32 images.
The current ones look pretty good and fit perfectly.

I'll answer our other discussions later.

BR

**Comment by harnnless** [comment]
@pnedev  x64 version still has the same issue, please take a look
![image](https://user-images.githubusercontent.com/17297532/66185329-a696a080-e6b1-11e9-82b9-e3141dcfe482.png)

**Comment by pnedev** [comment]
@harnnless ,
The fix is done and is OK but it is not officially released yet.
It will be in the new plugin called ComparePlus. I'm still working on it.
BR

**Comment by i3luefire** [comment]
Great work, thanks all.
