### ISSUE TITLE
[Feature Request] highlight added words as green in a diff line. 

### ISSUE THREAD

**Issue by MetaChuh** [pnedev/compare-plugin#196]
hi @pnedev 

currently added words and deleted words in a line diff, are both highlighted in the same colour orange, as defined by the <kbd>Change highlight</kbd>  colour at the settings.

**feature question**: would it be possible to:
* separate the line diff <kbd>Change highlight</kbd> colours in the settings for left and right panel.
* <kbd>Change highlight (R)</kbd> to highlight all added sections of a line in green (right panel only)
* <kbd>Change highlight (L)</kbd> to highlight all removed sections of a line in red (left panel only)

i know, this is not standard for diff tools (except maybe atlassian fisheye), and ComparePlus currently looks exactly like expected and similar to other diff tools i use,
but do you think that this feature would be cool enough, to make ComparePlus stand out even more from the rest ?

**biggest question**: are separate highlight colour settings for left and right panels possible to implement without major troubles ?

example screenshot:
![Imgur](https://i.imgur.com/L5Ia38T.png)

atlassian fisheye diff view screenshot:
the trouble making cause of my feature request, now that i've seen it, i can not unsee it 😉
(note: this is only a red/green example, as i don't know if i like all of the fisheye look.)
![img](https://confluence.atlassian.com/fisheye/files/960155326/960155329/1/1540460169949/Crucible_2.2-Side-by-Side-Diff_Main-View-RAW-70.png)

many thanks, greetings, best regards, and sorry for writing that much again.

**Comment by pnedev** [comment]
Hi @MetaChuh ,

> feature question: would it be possible to: ...

That is an interesting idea, cool :+1: 

I imagine the case when the compared files have only changed lines (yellow). Then your idea is very good because the green / red marked changes in the lines will still signify which of the files is the new one and which is the old.

> biggest question: are separate highlight colour settings for left and right panels possible to implement without major troubles ?

Well, it can be done and it's not that troublesome on first look.

GitHub even uses light-red and light-green for changed lines but then we'll need two separate settings for changed lines colors for each of the files which is something I don't like. I suppose you'll want to set the changed line color to white to mimic fully atlassian fisheye diff marking.

Yaron, what do you think about that?

Thanks for the idea @MetaChuh :+1: 

BR

**Comment by MetaChuh** [comment]
hi @pnedev 

thanks for your quick reply.

> but then we'll need two separate settings for changed lines colors for each of the files which is something I don't like.

oh, it was just a quick and dirty workaround idea to differ the settings for both panels, if this would be easier to code.
but you are absolutely right, same unified settings for both panels with e.g. <kbd>Change added highlight</kbd> and <kbd>Change removed highlight</kbd> instead of a single <kbd>Change highlight</kbd> would of course be the non-plus-ultra perfect solution.

> I suppose you'll want to set the changed line color to white to mimic fully atlassian fisheye diff marking.

not really, as i'm more used to the compare plugin or winmerge look, i only took the atlassian screenshot, because it was red and green styled for changed lines.

i don't mind the line background of the diff lines to remain as they are, defined with a single<kbd>Changed line</kbd>, or any other solution you would like.
it would be enough if the added text in a diff line could be marked in green, just the segment that i marked in the first screenshot, unless you would like more.

please don't take anything i wrote as a fixed request, more of brain storming inputs without thinking everything through.
and in the end, you are the only one who can come up with the best ideas, directly while coding, especially if the red/green scheme is of interest to you and gets stuck in your mind.

i guess my main motivation to ask you, is because i had that less experienced community user in mind, thinking that i hope he will know which of his diff parts are the added ones and which are the removed ones. 😉

greetings and best regards to all

**Comment by Yaron10** [comment]
Hello Pavel and @MetaChuh,

This is indeed a nice suggestion which can be helpful in many cases. :+1: 

CP uses a different color for Changed lines so that the user can instantly know whether the lines are related or not: green/red lines are not related/similar and brown lines are.

Marking inline-changes in green/red may cause confusion if the changed line is surrounded by Added/Removed lines. 

What do you think @MetaChuh?
If you still want an option to mark inline-changes in green/red (and Pavel is kindly willing to implement it), I'd suggest to set the default color of both `Old file inline-changes highlight` and `New file inline-changes highlight` to the current color.

Thank you.
BR

**Comment by MetaChuh** [comment]
hi @Yaron10 

> Marking inline-changes in green/red may cause confusion if the changed line is surrounded by Added/Removed lines.

yes, you are absolutely correct, it must not create confusion under any circumstances, so it should not be a visual overkill, but just a slight optic improvement, even for all users that are used to the way it is.

i've made a little mockup screenshot for you, to check if these changes would confuse, or if the additional colour would be an improvement if implemented in ComparePlus, even to long year Compare plugin users.
what do you think about this view ?

![Imgur](https://i.imgur.com/WYNdJkL.png)

notes:
* the optical colour mixing scheme is kept from the original cp plugin.
* deleted texts in diff lines are shown as usual, with a mixture of the <kbd>changed line</kbd> background colour, and the <kbd>removed line</kbd> background colour, resulting in the orange <kbd>changed highlight</kbd> colour we all are used to.
* same scheme, but mixing the <kbd>added line</kbd> colour with the <kbd>changed line</kbd> colour is applied to achieve the green, but not too light green mixture for added texts.


here is a comparison picture of the current old original view:

![Imgur](https://i.imgur.com/RbvAxsg.png)


> If you still want an option to mark inline-changes in green/red (and Pavel is kindly willing to implement it), I'd suggest to set the default color of both Old file inline-changes highlight and New file inline-changes highlight to the current color.

i wouldn't mind at all, if both colours are the current orange <kbd>changed highlight</kbd> colour as default, if you decide this would make sense.

and, most important, i wouldn't want @pnedev to implement any of that, if he doesn't like it for himself.

many thanks and greetings

**Comment by pnedev** [comment]
Hello @MetaChuh  and @Yaron10 ,

Thank you both for the feedback, I appreciate it. :+1: 

@MetaChuh , thank you for the screenshots. Visualizing the idea is very helpful.

I personally find the current coloring visually more appealing. It may be because I'm used to it, I don't know. The green in the added highlight might be confused with Notepad++ selection highlighting (when you select a word and all its other occurrences are highlighted).
But it is really no problem to make separate highlight settings for both views if some users will find it useful.
I agree with Yaron that the default should be the current coloring.

So the question is will some users find such separate setting useful?
What do you think?

Thanks again and
BR

**Comment by MetaChuh** [comment]
hi @pnedev and all

thanks for your answers.

> So the question is will some users find such separate setting useful?
What do you think?

i can only assume that it would be visually helpful ... except for italians of rome, they ignore all red/green traffic lights anyways 😉

if you think this could be a nice plus feature and not too hard to implement, you could e.g. ask at the community by showing mockup screenshots, or anything else you would prefer to show.
(this might also serve to promote the upcoming ComparePlus a bit, by combining such inquiry with introducing the features you've already added)

big thanks and greetings

**Comment by pnedev** [comment]
Hi @MetaChuh ,

Ok then, I'll consider implementing it (despite the Italians  of Rome ;) ).
Thank you. :+1: 

BR

**Comment by Yaron10** [comment]
Hello,

@MetaChuh,
Thanks again for the suggestion and the screenshots. :+1: 

Isn't it even worse in Naples? :)

Pavel,
Thank you for that too. Your hard work is much appreciated. :+1: 

BR

**Comment by pnedev** [comment]
Hello guys,

The new feature is implemented in this x86 binary:
https://ci.appveyor.com/api/buildjobs/1e3mfawmtp1qag9e/artifacts/ComparePlus.dll .

Please write back if something doesn't seem right. Thanks.

PS. I haven't fully tested it yet because under Wine the color settings do not work.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

It seems to be working like a charm. :+1: 

Thank you.
BR

**Comment by MetaChuh** [comment]
@pnedev 

wow, this is awesome and hyper-quick !!! 👍

here's a screenshot of it in action:
![Imgur](https://i.imgur.com/CkTG86H.png)

-----

> PS. I haven't fully tested it yet because under Wine the color settings do not work.

i currently don't mind, as i can edit the `ComparePlus.ini` manually.

screenshot of the missing colours and colour picker on wine:
![Imgur](https://i.imgur.com/7SKuCc5.png)

do you know what causes the missing colour picker and colour display at the compare code on wine ?
is there anything you could use from the npp style configurator colour management, as the styler colours work on wine ?

npp style configurator on wine: 
![Imgur](https://i.imgur.com/qu40ZTF.png)

big thanks, a big group hug, and i owe you a big beer 😉

**Comment by MetaChuh** [comment]
closing with https://github.com/pnedev/compare-plugin/commit/8a94e6828a125740fc122cac27024818d2949769

**Comment by pnedev** [comment]
Hello @MetaChuh  and @Yaron10 ,

Sorry for the late reply guys and thanks for testing.

@MetaChuh ,

> i currently don't mind, as i can edit the ComparePlus.ini manually.

Yeah, good point, but I wanted to test the Settings dialog as well.
I don't know what causes the missing colors in Setting on Wine. I suspect it is due to some missing Wine libraries or partially implemented ones.

BR
