### ISSUE TITLE
hangs / crashes notepad++ 7.5.9, 64 bit

### ISSUE THREAD

**Issue by ackerman76** [pnedev/compare-plugin#198]
Hung and crashes notepad++ after about 30%. Cannot cancel.

**Comment by pnedev** [comment]
@ackerman76 ,
What do you mean by "crashes notepad++" ?

If it simply hangs then I suppose you are comparing either very big files or very different files (with lots of changes).
You need to wait longer. I know there is no indication of something happening but the compare is still running.

**Comment by ackerman76** [comment]
Oh yes, I just let compare plugin complete and it took 9 minutes ROFL, using 24% of my 6 cores!

Yesterday I just gave up and opened a command window in VisualStudio and typed:
Tools.DiffFiles pathFile1 pathFile2

And it diffed immediately. VisualStudio is amazing by comparison to Notepad++, which freezes as I scroll. Microsoft has been putting a lot of effort into VisualStudio since 1997 so that's why it is so good.  Thanks

**Comment by pnedev** [comment]
@ackerman76 ,

You are right, Visual Studio is a great product.
Please feel free to use it instead of Notepad++ and Compare plugin.

Thank you for the feedback, I appreciate it.

**Comment by userdocs** [comment]
Hopefully i can elaborate on this as this sound like an issue i experienced.

Using the current appveyor build with x64  `git2.dll` from your repo. 

Let's say i have 400 lines and they differ by one word.

File one

~~~
cmd -cf /one/ /to/this/dir
~~~

File two

~~~
cmd -cf /two/ /to/this/dir
~~~

This happens. 

![example](https://user-images.githubusercontent.com/16525024/58387973-d650e000-800f-11e9-9b6b-fc1babafc79b.jpg)

It does not ever complete. The only way recover is use the not responding prompt and force close the program.

The replication of the problem seems to be linked to a single component of the compare being different across a large volume of lines.

**Comment by pnedev** [comment]
Thanks @userdocs ,

I know what causes this and I'm working on a fix.
I've marked the issue as `illegal` because neither the plugin crashes, nor it crashes Notepad.
The change detection algorithm in certain cases takes VERY long time.

**Comment by userdocs** [comment]
You're welcome @pnedev.

Aside from that i find your plugin immensely useful and use it all the time. That was the only real issue i ever experienced for my day to day casual compares without leaving notepad.

**Comment by pnedev** [comment]
OK, I have finally made this much better in the current development stage.
Having many very similar lines is still the most tedious compare case but now it is faster and you also have much more informative progress indication and more responsive cancel.

The fix will be in the new plugin release.
