### ISSUE TITLE
[Bug] No more undo action available after running "Compare" command

### ISSUE THREAD

**Issue by pidgeon777** [pnedev/compare-plugin#208]
Here is what happens:

1. You choose the first file to be compared.
2. You choose the second file to be compared and run the "Compare" command.
3. You modify some text of either one of the files in the side-view comparison preview.
3. You run the "Compare" command again.

This leads to a refresh of the compare window but also to a deletion of the undo history as an effect. So it is not possible anymore to revert back the changes done to the file (for example through Ctrl+Z). The file will still be marked with a red sign, though, informing that it has been modified without saving it. But still, with no further undo action available.

This is a very annoying bug which dramatically lessens the usability of this plugin during the "Compare" mode. Hopefully, it will be possible for you to fix this issue, it would make this plugin a lot better.

**Comment by pnedev** [comment]
@pidgeon777 ,

This is already fixed in the new plugin release (coming soon).
Only on rare occasions the undo list will be deleted (when there is a difference in the very first line of the document). It is currently not possible to fix this (due to Scintilla limitation) but hopefully this will happen rarely and can be worked around if new line is inserted in the beginning of the file.

Thanks.

**Comment by pidgeon777** [comment]
Thank you. Hopefully, that special condition will occur rarely.
