### ISSUE TITLE
No plugin in menu

### ISSUE THREAD

**Issue by okainov** [pnedev/compare-plugin#213]
What I tried:

- Installing plugin from NPP Plugin Admin
- Copying plugin files manually to "Plugins" folder
- Copying plugin files manually to "Plugins\\ComparePlus" folder (as mentioned in a readme for some reason)

None of those work, plugin is not appearing the the Plugins menu.

Npp 7.7 32-bit
Windows 10

**Comment by xylographe** [comment]
```
\plugins\ComparePlugin\ComparePlugin.dll
\plugins\ComparePlugin\ComparePlugin\git2.dll
\plugins\ComparePlugin\ComparePlugin\sqlite3.dll
```
The `\plugins` directory must be located in the directory that contains the file `notepad++.exe`.
Installing plug-ins below `%APPDATA%\Notepad++` is not possible in NPP 7.7 and later.

**Comment by okainov** [comment]
Oh, seems it was important to have the very same name for the folder and DLL. Now it works for me. But these issues are still here:

- Readme is not in sync with actual files. Files are "ComparePlugin" but readme refers to "ComparePlus"
- Installation from PluginAdmin from NPP doesn't work...

**Comment by xylographe** [comment]
ComparePlus is the name of the next generation Compare plug-in, which has not been released yet.

There are more than a few people reporting that installing plug-ins (not limited to Compare) with the new PluginsAdmin doesn't work. I believe this is due to the built-in PluginsAdmin being less robust than the former PluginManager. Also, plug-ins are no longer downloaded from a central server, but directly from a location determined by the plug-in's developer (typically GitHub, SourceForge, etc.).

**Comment by xylographe** [comment]
BTW if you open the `\plugins\Config\nppPluginList.dll` file in NPP, and search for `"npp-pluginList"` you can see the details (`"folder-name", `"repository"`, `"version"`, etc) for each plug-in.

**Comment by hexxor** [comment]
I had this too with Win 10 and Np++ 7.7.1 (32bit).
I fixed it by copying the ComparePlugin.dll also into C:\Program Files (x86)\Notepad++\plugins\ComparePlugin directory. I was using the manually downloaded ComparePlugin_v2.0.0_x86.zip

**Comment by pnedev** [comment]
Hi,

Sorry for the late reply.
@xylographe has answered very well, thanks :+1: 

I'll see what I can do about the readme.

BR
