### ISSUE TITLE
compare-plugin 200 still does not work in NPP 782 64-bits

### ISSUE THREAD

**Issue by noteovv** [pnedev/compare-plugin#219]
The title says it all.
Also see a previous issue for compare-plugin under NPP 771.
Manually installed in the NPP plugins folder, the dll and the folder ComparePlugin.
I even tried to create a ComparePlus folder and  even a folder named ComparePlugin, in order to put the dll and the folder with the other 2 dlls into that folder.
But nothing works.
I used the 64-bits compare plugin and I have the 64-bits NPP.

**Comment by pnedev** [comment]
Hi,

The title doesn't say it all at all.

> compare-plugin 200 still does not work ...

What exactly does that mean?
It doesn't load?
It doesn't appear in the menu?
It doesn't compare?
It crashes?

The dll **must not be** directly in the NPP plugins folder.
The dll + the ComparePlugin folder should be in
`Notepad++_install_folde\plugins\ComparePlugin\` folder like that:

`Notepad++_install_folde\plugins\ComparePlugin\ComparePlugin.dll`
`Notepad++_install_folde\plugins\ComparePlugin\ComparePlugin\*.*`

Please check that issue:
https://github.com/pnedev/compare-plugin/issues/184

Please also use this release:
https://github.com/pnedev/compare-plugin/releases/download/v2.0.0_npp7.7/ComparePlugin_v2.0.0_npp7.7_X64.zip

BR

**Comment by noteovv** [comment]
I have done exactly what you mentioned and I was referring to the same issue, entered by somebody else regarding version Npp 771.
Therefore I meant: Compare plugin does not show up in the Plugins menu of Npp.

Earlier, I downloaded the Compare plugin 200 npp 77 x64 from github/pnedev on Jan. 4 2020 and I installed it in Npp 771, 64-bits.
Nothing worked (i.e. Compare did not show up in the Npp 771 Plugins menu).
Then I downloaded the latest Npp 782 64-bits from the canonical website and I installed again the Compare plugin in several ways.
Also the way you mentioned, that is, in a ComparePlugin folder and in that folder the dll and the folder with the 2 additional dlls.

BUT, one day later, and having tried to install the Compare plugin again in a ComparePlugin folder and in that folder the dll and the folder with the 2 additional dlls, the Compare plugin DID show up in Npp 782, after a restart of Npp.
Now it works fine; it does compare two files with success!

It is quite possible that after the first installation of the plugin, something did not get registered (I'm using Windows 10).

So again and more verbose:
I ran Npp 771, 
noticed that Compare was not in the Plugins menu, 
quit Npp 771, 
downloaded Compare plugin 200, 
removed a previous version from the Npp\Plugins folder, 
installed the new Compare plugin manually, 
restarted Npp 771, 
noted that Compare plugin was not in the Npp Plugins menu, 
quit Npp, 
rearranged the Compare plugins locations (as mentioned above and as mentioned in the Npp forum),
restarted Npp 771, 
noted that Compare plugin was not in the Npp Plugins menu, 
then quit Npp 771, 
downloaded the latest version Npp 782,
installed it with the installer, 
removed Compare plugin files and folders from the Npp Plugins folder, 
installed Compare plugin again manually, 
started Npp 782, 
found that Compare plugin still wasn't showing up in the Npp 782 Plugins menu,
looked again at the dll locations, 
gave up, 
and wrote an issue.

Today I rearranged the Compare plugin folders and the dlls again in the Plugins folder of Npp, started Npp 782 again et voilà, the Compare plugin suddenly showed up in the Npp 782 Plugins menu and worked fine.

I can't help thinking that something does not get registered under Windows 10 when installing something, be it with an installer application or manually by copying/pasting files.
I also still believe that my issue was valid and that the authors of Compare and Npp should be aware of this type of problem.
Thanks for reading.

**Comment by pnedev** [comment]
Hi,

And thank you for the thorough description.
This sounds really strange. Notepad loads all its plugins dlls at start from its plugins folder and each plugin sub-folder there. If the paths have been correct then the only reason I can think of that might cause such problem is that Notepad has not been restarted after the plugin was copied to the correct place. Are you sure you have restarted Notepad when you manually copied the plugin?
If you have then perhaps you are right and Notepad registers somewhere its plugins.

Notepad++ (since 7.6 AFAIR) has this nice feature now called PluginsAdmin. You can find it in the plugins menu at the bottom. In the future you can use it to install / re-install the plugins you need and it is handy because it automatically gets the right plugin version and puts it in the right place + restarts Notepad.

BR

**Comment by noteovv** [comment]
Thanks for all your quick responses.

Like I described:
first quit Npp
then copy or move or rename objects in the Npp Plugins folder, as seen in Windows 10 Explorer
then start Npp again.

It could be that Npp doesn't get notified immediately by Windows of changes in the file system, or for a moment can't see changes made.

Anyhow, I was aware of the existence of PluginsAdmin, but, shall we play this game again? [haha].
I do not see a PluginsAdmin entry in the Plugins menu of Npp.
Not in Npp 771, not in 782.

Since automatically performed installations of updates or plugins have never worked in my Npp installations in the past 10 years or so, I do everything as much as possible manually.
It could be that application programmers are relying too much on their English version of Windows and are hard-coding something? I have a Dutch version of Windows.
Shouldn't make any difference for programmers, but I notice that there are more application programs that are not able to update my installation of _whatever_ from within the program itself.
For some programs it does work fine however.
So I can imagine that finding a solution for this problem is rather difficult.

**Comment by pnedev** [comment]
Thanks again for the explanation.
That is getting even more weird and, I don't know, you might be right about Win10 and the language.
I haven't heard of the behavior you described before though.
There were several Notepad++ versions after 7.6.x (so between 7.7 and 7.8 if I remember correctly) when there were a lot of debates where the plugins (and their configs) should reside and a lot of changes in that regard.
It can also be related to the user rights. As far as I know some features are not available if you are not running Notepad++ in admin mode (mainly the ones connected to the updates and additional plugins installations). Some people before weren't able to update or download plugins because they were behind a proxy.

I'm not sure if anything of the above applies to you but you can check several things:

1) Start Notepad, go to the question mark at the end of the menu (where the About is) and open `Debug Info...`. Check there the fourth line to see if the Admin mode is ON or OFF. If it is OFF then that's what might be causing your update issues and the missing PluginsAdmin.

2) Here is what I see from the Notepad++ v7.6.3 release notes at https://notepad-plus-plus.org/downloads/v7.6.3/ :
>
