### ISSUE TITLE
Incorrect compare results

### ISSUE THREAD

**Issue by hexep** [pnedev/compare-plugin#227]
There are unnecessary breaks after comparing some files (for example, "russian.xml" and "english.xml" files of notepad++).

![image](https://user-images.githubusercontent.com/29166409/74240315-c9356780-4cea-11ea-8399-8265b04eba98.png)

**Comment by xylographe** [comment]
Try enabling **Plugins > Compare > Ignore Spaces**. The files have different indentation style.

**Comment by pnedev** [comment]
@hexep ,

Do you mean the blank lines 25-71 or you are talking about the changed spaces marked with dark yellow / orange ?

What @xylographe suggested will ignore the changed spaces (my second guess) and those will no longer be marked.

If your problem is my first guess you cannot do anything about it - lines 25-71 simply match, they are the same and compare as equal.

**Comment by xylographe** [comment]
@pnedev 
I think the OP prefers something with fewer ‘gaps’, like this,

![NPPComparePlugin](https://user-images.githubusercontent.com/8535293/74281323-87beaf80-4d1e-11ea-9295-278953ef8b08.png)

With "Ignore Spaces" enabled most lines will be considered similar, resulting in fewer gaps.

**Comment by pnedev** [comment]
@xylographe ,

Thanks for explaining. Perhaps you are right. :+1:

**Comment by hexep** [comment]
@xylographe,

Thanks, it helped me.
