### ISSUE TITLE
Typing in Incremental Search Bar moves focus to editor

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#241]
Hello Pavel,

I hope you're in good health and not as busy. :)

**STR:**
Compare.
Type a letter (existing in the file) in the Incremental Search Bar.

**Result:**
The focus moves to the editor.
If you want to type `abc`, `bc` might be typed in the editor.

Probably a relatively recent regression.
***
Please reply whenever you have time.

Thank you and BR.

**Comment by pnedev** [comment]
Hello Yaron,

Thank you for filing this issue, I'll have a look soon.

I am good, thanks, hope you are doing well too.
Take care.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thanks for replying - I'm glad you're OK.

And thank you for looking into it. Whenever you find the time.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

It's been a long time again. 
I hope you're doing well.

I use the Incremental Search Bar quite frequently. - I had a look at it myself. :)

It seems that removing `::SetFocus(getCurrentView());` from
```
		else
		{
			if (realign)
				storedLocation->restore();

			syncViews(storedLocation->getView());

			storedLocation = nullptr;
			cmpPair->setStatus();

			::SetFocus(getCurrentView());
		}
```
solves the problem.

But I'm sure it's there for a reason.
If it's not too much trouble for you now, could you please let me know what issue might be caused by removing it?

Thank you.

I wish you the best.

**Comment by pnedev** [comment]
Hello Yaron,

You are a "dream user" - you file an issue and then fix it on your own :))

I have submitted the changes you suggest ([**x86 binary**](https://ci.appveyor.com/api/buildjobs/9c0nhrk30ev4ap6u/artifacts/ComparePlus.dll))
Honestly, I can't remember why the `SetFocus` calls were there - it seems those are not needed. My quick tests didn't show any problems but we'll see if some regressions appear in the future.
I might have put them because back then I had some issues with the focus due to specifics connected with Wine.

Thanks for writing.
Let's hope it won't be long before we "talk" again :)

All the best

**Comment by Yaron10** [comment]
Hello Pavel,

Needles to say I consider you the "dream developer". :)

> I have submitted the changes you suggest...

Great. :+1: 

I'm glad you've found the time to look into it. Thank you.

> Let's hope it won't be long before we "talk" again.

I'm certainly looking forward to that. I do hope you get the time and mood. :)

BR
