### ISSUE TITLE
AddedRemoved instead of Changed

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#243]
Hello Pavel,

I don't want to bother you now. Whenever you're ready.

Paste the following lines into OldA.
```
user_pref("plugin.flash.lastmod_hi", 370);
user_pref("plugin.flash.lastmod_lo", -1612630950);
```
Paste the following lines into NewA.
```
user_pref("plugin.flash.lastmod_hi", 371);
user_pref("plugin.flash.lastmod_lo", 1355675797);
```

Compare the files when OldA is Old and NewA is New.

Result:
Lines 2 are marked as AddedRemoved instead of Changed.
(If you delete line 1 in both files, the compared line is marked as Changed).

Thank you.
BR

**Comment by pnedev** [comment]
Hello Yaron,

I'll have a look, thank you for reporting this.
If the files have different number of lines it will not happen BTW.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you for replying and looking into it.

Have a nice weekend and a pleasant time in general. :)

**Comment by pnedev** [comment]
Hello Yaron,

The issue is fixed and here are the new development binaries:
- x86 : https://ci.appveyor.com/api/buildjobs/vtfv2my0p5hgc541/artifacts/ComparePlus.dll
- x64 : https://ci.appveyor.com/api/buildjobs/xy98s65jxlxcwwx8/artifacts/ComparePlus.dll

Those are not suitable for N++ versions above 7.7 (included). Sorry for that but I'm using 7.6.6 as my development build. The new Scintilla headers will be used for the final release. You can use safely the x86 build with versions above 7.7 as well but not x64.

Thanks once again for catching that issue and for reporting it :+1: 

All the best!

**Comment by Yaron10** [comment]
Hello Pavel,

:+1: 
Great!

I'm glad you found the time to fix it. Much appreciated.

The `+ - 5` in Settings is nice. :)

BR
