### ISSUE TITLE
Unexpected slow compare with CSV files

### ISSUE THREAD

**Issue by ChliHug** [pnedev/compare-plugin#247]
I encountered two CSV files that take an unexpected long time to compare. There are a few other issues where it is explained that this might be expected behavior due to how the plugin does the comparison. Is it possible that's also the case here?

[csv_example_files.zip](https://github.com/pnedev/compare-plugin/files/5079830/csv_example_files.zip)

These CSV files are from Microchip's Parametric Search Tool. They recently added two new columns before the last column and this change made the comparing so slow.

**Comment by pnedev** [comment]
@ChliHug ,

Yes, these are difficult files to compare.
The addition of the two new columns makes the files totally different.
What I mean is that practically the files have no two completely matching lines and Compare needs to look all the lines for partial similarities. Because there are a lot of lines and they are also quite long it makes the process even harder (and slower). The similar lines have also changed order in several places.
Unfortunately there is nothing we can do about that. If you'd like to see the existing similarities between the lines you'll have to wait.

**Comment by ChliHug** [comment]
I understand. Thanks for looking into it.

**Comment by pnedev** [comment]
@ChliHug ,
No problem.
You can speed-up things by manually inserting one empty line after each 50 lines in both files but this might reduce the accuracy of the found similarities because the order of the processors in the list had changed.
The number 50 here is not fixed - the smaller the faster and the less accurate. It is good to keep that number equal in both files though.
