### ISSUE TITLE
[Bug] After file change and compare it is not possible to undo anymore

### ISSUE THREAD

**Issue by pidgeon777** [pnedev/compare-plugin#248]
Hi, I'm using Compare Plugin version v2.0.0, Notepad++ v7.8.2.

When comparing two files, if I modify one of them subsequently comparing them again, it is not possible to undo anymore (even the undo icon is greyed out).

**Comment by pnedev** [comment]
Hi @pidgeon777 ,

That is a known issue for Compare version 2.0 (and before that). It is how it is supposed to work.

The new plugin (ComparePlus) does not have that problem. Let's hope I'll release it someday (I stopped promising people when this is supposed to happen because I changed the date several times already).

BR

**Comment by nileplumb** [comment]
this bug has finally shown itself to me unsure how I've managed to avoid it all this time

**Comment by pnedev** [comment]
Implemented/fixed and will be included in the first ComparePlus plugin release coming in a month or so.
