### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by CC007** [pnedev/compare-plugin#255]
When trying to install the plugin through the Plugins Admin interface, notepad++ closes after hitting the install button and doesn't start back up automatically. When opening notepad++ manually afterwards, the plugin is not installed.

The manual installation of the plugin did work without issues (after I found out I had to put it one folder deeper)

**Comment by pnedev** [comment]
Hi @CC007 ,

The installation of the plugin through Notepad++ Plugin Admin is not related to the plugin itself - it is an issue with Notepad++ and Plugin Admin. That's why I'm going to close this issue report but thanks for filing it anyway.

Some info:
Plugin Admin tries to get the plugin you wish to install from a URL that is pre-configured when your Notepad++ version was released. That URL should be the place where the appropriate plugin release resides BUT:
sometimes the URL might be unreachable - URL server down or temporary no internet traffic to the server (that may include temporary issue with your network) or firewall blocking the access.
Most often users report that problem with any plugin they want to install via Plugin Admin when they are behind a proxy (you can check Notepad++ forums for the solution of that problem - it is a dedicated config of the Plugin Admin).

I'm glad you managed to manually install Compare without problems.

**Comment by CC007** [comment]
Oh yea, the proxy. Forgot about that. Thanks for the reply.
