### ISSUE TITLE
Icons not visible with Notepad++ dark theme

### ISSUE THREAD

**Issue by Eenpersoonscommissie** [pnedev/compare-plugin#261]
Hi, Notepad++ v8.0 introduced the possibility for a dark ui-theme. With is there is an empty space where the compare buttons should be (they are there, but invisible). The rest of the icons (not only native ones) are shown in a light version. Apparently Notepad++ has a way to switch these if light icons are available (like in f.e. Nextcloud you can use name.svg and name-dark.svg as icons).

**Comment by pryrt** [comment]
specifically, plugin authors need to call NPPM_ADDTOOLBARICON_FORDARKMODE instead of NPPM_ADDTOOLBARICON if version 8 or newer.  (Actually, I don't think it hurts to call both, to keep the plugin compatible with older versions...)

**Comment by CypherAus** [comment]
The icons are there (invisible) just mouse over and the tip pops up or use the compare menu items as a work around until resolved.
The Dark theme is great.  Compare is a great plugin!

**Comment by pnedev** [comment]
Hi @Eenpersoonscommissie ,

I have stopped supporting the ComparePlugin but I have been planing on releasing a new Compare plugin that is a very enhanced descendant of it which will be named ComparePlus.
Unfortunately its development is stalled for a very long time now (8 months or so) due to my busy schedule.
I will have your request in mind when I continue with the development.

BR

**Comment by chcg** [comment]
See also https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10131

**Comment by CennoxX** [comment]
This was a bug on notepad++'s side that affected also other icons, it is fixed with 8.1.4.

**Comment by pnedev** [comment]
Implemented/fixed and will be included in the first ComparePlus plugin release coming in a month or so.
