### ISSUE TITLE
Calling Reset() after compared files have been closed

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#27]
Hello Pavel,

I've tried to zoom in a bit (i.e. I've taken a second look at some parts of Compare.cpp) and found that Reset() is called if the user selects to close both compared-matched files.

It seems that some parts of Reset() are irrelevant in this case. 
(Actually , this is true even if the files do not match and the user closes one or both).

I assume you've already noticed that. Just in case. :)

Thank you very much.

Best regards.

**Comment by pnedev** [comment]
Hello Yaron,

> I assume you've already noticed that.

I haven't actually, thanks for pointing this out.
I was busy with other parts of the code and haven't reviewed that part yet.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thanks again for your remarkable work.

BR

**Comment by pnedev** [comment]
Hello Yaron,

This is not relevant anymore due to the new implementation so I'm closing this issue.

One question:
What do you think about showing "Close compared files" question dialog in case the user cancels the compare process or if one of the files is empty?
This will also make the implementation more straightforward.
Thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

> This is not relevant anymore due to the new implementation so I'm closing this issue.

Great. :+1: 
Many thanks.

BR
