### ISSUE TITLE
Changed or different lines

### ISSUE THREAD

**Issue by Spanden** [pnedev/compare-plugin#270]
How to change the setting for determining which string is: changed or new?
The first 4 characters match in my strings, but because of the long length of the string, it is highlighted as new. But I need it to be highlighted as changed.

**Comment by pnedev** [comment]
Currently there is nothing you can do to change that.
Compare does its matching based on whole words and not separate characters.

**Comment by jocker-il** [comment]
Is it same as this ? or is this a different issue - talking about the difference of lines like 63, 67, 75, 79 & 82  - why are they marked as 'Added' in the default config file VS 'Deleted' in the current config file while the lines around them have the same differences and are marked as 'Changed' which makes sense to me ?

![image](https://user-images.githubusercontent.com/13031901/167482081-d9795e7a-94b3-4d78-9be0-319849246745.png)

**Comment by pnedev** [comment]
@jocker-il ,

I cannot load the image at the moment. I'll get back to you when I check it.

**Comment by pnedev** [comment]
@jocker-il ,

OK, I saw your image, thanks for uploading it.
The lines are not marked as changed because of the size of the parts that differ. Compare works in a way that there is an internal threshold that determines if the mismatching lines are to be considered "changed" or completely different.  That threshold is percentage of the matching portions of the lines related to the size of the bigger of the lines.
So since the lines mentioned by you are longer by others they seem to be under the internal threshold and are thus considered completely different.

In the new plugin I'm working on (will be called ComparePlus) that threshold is configurable in the Settings and also there is another criteria for deciding which lines are to be marked changed that can be selected over the current threshold approach.
You can try it when the new plugin is released.

**Comment by pnedev** [comment]
Implemented/fixed and will be included in the first ComparePlus plugin release coming in a month or so.
