### ISSUE TITLE
Can you add an option to Ignore Case?

### ISSUE THREAD

**Issue by bsacheri** [pnedev/compare-plugin#271]
I am curious if there is a way to make Compare ignore case values in letters. I am using Compare to compare differences in email address lists, and it recognizes that 2 addresses are different if the only thing differing between them is the case value (upper versus lower).  I am also using it to compare SQL which is not case sensitive.

I saw a mention of an "Ignore Case" option in another post but I don't see it in my installation of v2.0.1.

**Comment by pnedev** [comment]
@bsacheri ,

I've been preparing a new plugin called ComparePlus that is meant to be successor or the current plugin and it has the functionality you mention. It is almost finished but unfortunately is in that state for quite some time now (probably a year or even more) due to my busy schedule. I hope I can finish its first official release soon but I cannot give you a date or promise anything now.

**Comment by bsacheri** [comment]
Thanks for the quick response.  I'll try to be patient and hope you can make progress on it over the winter.

👍

**Comment by pnedev** [comment]
Implemented/fixed and will be included in the first ComparePlus plugin release coming in a month or so.

**Comment by bsacheri** [comment]
Excellent!   It's a good feeling to make some progress on a volunteer
project.   I'm currently injured and can't leave the house so I've been
doing the same on some of my pet projects with AutoHotkey scripts.

Cheers!

Ben
Pittsburgh, PA  USA

**Comment by pnedev** [comment]
Oh, sorry to "hear" about your injury. I hope you to get better soon. Good for your home projects though ;)
Finding any spare time is getting more and more difficult these days (at least for me).
Take care :+1:
