### ISSUE TITLE
Notepad++ 8.2.1 forcing ComparePlugin v2.0.2 (not compatible)

### ISSUE THREAD

**Issue by jcstevensri** [pnedev/compare-plugin#281]
Notepad++ disabled my working 2.0.1 ComparePlugin. When I went into the Plugin Manager and searched for ComparePlugin, the only version available was 2.0.2. Running Notepad++ 8.2.1 with ComparePlugin 2.0.2 crashes Notepad++ upon selecting a file for comparison.

I saw the note here that 2.0.2 only works with Notepad++ 8.2.2+.

To resolve, I had to close Notepad++ and copy the 2.0.1 ComparePlugin.dll from the 'disabled' folder into the 'ComparePlugin' folder.

**Comment by pnedev** [comment]
@jcstevensri ,
It appears that the PluginsList of Notepad++ v8.2.1 is not correct.
Every Notepad++ version comes with a list of compatible plugins (available for installation through its Plugins Admin) and it is its responsibility to point to the correct plugins versions.

You could report that mismatch either in plugins list repo: https://github.com/notepad-plus-plus/nppPluginList
or in Notepad++'s forum: https://community.notepad-plus-plus.org/

**Comment by jcstevensri** [comment]
Reported to Notepad++ Plugin Forum - https://community.notepad-plus-plus.org/topic/22651/notepad-8-2-1-incompatible-with-compareplugin-2-0-2

**Comment by pnedev** [comment]
Thanks @jcstevensri .

I saw the thread in Notepad++ community page and noticed Peter's reply there.
It appears that Notepad++'s Plugins Admin is pointing to the right Compare plugin version as tested and reported by Peter.

So perhaps indeed you are still using Plugins Manager (it is Notepad++'s plugin itself) and talking about it rather than the built-in Notepad++ Plugins Admin functionality and the later is the only official plugins source. The validity of Plugin Manager's links is not guaranteed (by others than its author) so those might work or not.
I would suggest you to use only the built-in Notepad++'s Plugin Admin (you will find it near the end of Plugins menu).
