### ISSUE TITLE
Option to see statistical information.

### ISSUE THREAD

**Issue by JazzfanRS** [pnedev/compare-plugin#285]
I just reinstalled Compare. I don't know what the current version is. Running on Windows 7.

Would like to see option to view statistical information about the comparison. Placement of information ideally placed in truncated NavBar.

My scenario is two +/- 30,000 line files, with very little white space. The two files have about 200 - 300 identical lines (including moves) scattered within the 30k lines. Manual count is a poor option, as would be editing to place them together.

Suggestions I try while I wait? I can't code my way out of a paper bag. Thanks!

**Comment by pnedev** [comment]
I did not understand what statistical information exactly you need.

The new compare plugin I'm working on - ComparePlus shows statistics like number of added/moved/matched/removed lines but it is not released yet.
If you want you can try it by manually installing the current development binary but it is for Notepad++ versions above 8.3.3 (included). You'll need [32 bit](https://ci.appveyor.com/api/buildjobs/ok55wwstgyr7x640/artifacts/ComparePlus.dll) build if your Notepad++ is 32-bit or [64 bit](https://ci.appveyor.com/api/buildjobs/kbnlw5l0vpyq6v69/artifacts/ComparePlus.dll) otherwise. You can check your Notepad++ "bit-ness" in its About info.
When you download the correct DLL from the links place it manually in your Notepad++ plugins folder under sub-folder named `ComparePlus`.

The statistic numbers are displayed in Notepad++'s status bar in the down left corner of the window.

**Comment by JazzfanRS** [comment]
What you described is the features I needed. 

Two 30,000-line files with no dead space (empty lines, tabs, or spaces). I had used compare plugin on another machine years ago and wanted NP++ and plugins on it as well. My request was made before I looked into what else was in the GitHub. (I recently signed up).

I followed directions to install it manually, but having problems with it showing up in NP. This is a problem on my end I need to sort out. 

Running NP 8.3.3 x64, should I not uninstall ComparePlugin 2.0.2? And just replace the compareplugin.dll with compareplus.dll? 

If I am unable to load it, I will just continue with 2.0.2 and watch for the new release.

**Comment by pnedev** [comment]
> Running NP 8.3.3 x64, should I not uninstall ComparePlugin 2.0.2? And just replace the compareplugin.dll with compareplus.dll?

You can leave ComparePlugin 2.0.2 and just replace the ComparePlugin.dll with ComparePlus.dll from https://ci.appveyor.com/api/buildjobs/kbnlw5l0vpyq6v69/artifacts/ComparePlus.dll BUT you MUST also rename ComparePlugin subfolder where the DLL is located to ComparePlus.
So finally you should have `Notepad++\plugins\ComparePlus\ComparePlus.dll`

**Comment by JazzfanRS** [comment]
Okay, thank you it's working now! Thank you!

**Comment by pnedev** [comment]
Implemented/fixed and will be included in the first ComparePlus plugin release coming in a month or so.
Command to show statistics is also added to avoid problems with readability due to truncation.
