### ISSUE TITLE
Compare to Clipboard: Some Questions

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#303]
Hello Pavel,

Could you please try the following cases?

**1.**
Have a file containing one line `Test`.
Select All.
Copy.
_Remove selection_.
Compare to Clipboard.

**Expected:**
File and Clipboard match.

**2.**
Have a file containing one line `Test Test`.
Select `Test`.
Copy.
Compare to Clipboard.

**Expected:**
Selection and Clipboard match.

**3.**
Have a file containing _two lines_ `Test` + an empty line.
Select All.
Copy.
_Remove selection_.
Compare to Clipboard.

**Expected:**
File and Clipboard match.

**4.**
Have a file containing _two lines_ `Test` + an empty line.
Select All.
Copy.
Compare to Clipboard.

**Expected:**
Selection and Clipboard match.

Thank you for looking into it.

BR

**Comment by pnedev** [comment]
Hello Yaron,

I'll comment in a few days, thank you.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Whenever you have time.
I appreciate it.

Have a nice weekend.

**Comment by pnedev** [comment]
Hello Yaron,

Just before you created this issue I did some changes to `Compare to clipboard` functionality.

Let's briefly go over the points you listed in regards to the current implementation:

1) This is working as you suggested in the latest implementation.

2) Unfortunately that expectation cannot be currently met. The selections that CP gets to compare are line-based. They cannot be parts of a line. On the other hand the clipboard can contain anything no matter from where it is copied.
So when we select and copy "Test" from the file in Notepad the clipboard contains just that. But if we do direct compare that way the selected part "Test" is transformed to the whole line "Test Test" and that line selection is compared against clipboard.
On the other hand when we do "Selection compare to clipboard" the clipboard content is also preceded by one empty line (just in the beginning) to help alignment. This leads to the result you noticed. If the clipboard compare is against the whole file (not selection) then the leading empty line is not inserted in clipboard.
You can for example try creating a file with two matching groups of lines. Then copy the first group to clipboard, select the second group and do "compare selection to clipboard":
Example file:
"
line1
line2
line3
line1
line2
line3
"
This is an example of a very common (AFAIU) use-case.
You can also try comparing the clipboard to the whole file and also make the groups slightly different (for example change the first "line2" to "line2 new".

The main point is that Selection compare CP feature is line-based. It is not intended for partial lines compare.
Clipboard selection compare is actually a Selection compare and has the same limitations.

3) This is working as you suggested in the latest implementation.

4) This doesn't lead to a match because there is a selection and as described in point 2 a leading empty line is added to clipboard content. It is a corner case that I can fix by removing selection if the whole file is selected and then the clipboard will be kept as-is (without the leading empty line). This way the result will be a match.
Tell me what you think.

Thank you for the feedback Yaron, I appreciate it.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you for the detailed explanation. I appreciate it.

> It is a corner case that I can fix by removing selection if the whole file is selected and then the clipboard will be kept as-is (without the leading empty line). This way the result will be a match.
Tell me what you think.

It's not only this corner case.

```
line1
line2
line3
line1
line2
line3
```

Copy those lines and paste them in NPP.
Copy *here* the first 3 lines and select them them in NPP.
Compare to Clipboard.

**Result:**
As expected: match.

Copy those lines and paste them in NPP.
Select the first 3 lines in NPP and Copy.
Compare to Clipboard.

**Result:**
Not a match.

And this is a rather common case.

Thanks again.

BR

**Comment by pnedev** [comment]
Hello again Yaron,

The second case result is a match on my side.

I think I know what might have happened.

In the first case you have copied the text from _here_ which is done on "char-by-char" basis.
In the second case perhaps you have copied the three lines on a "line" basis in _Notepad_ (selecting them through the lines number margin). However this is not the same because the last copied symbol (if that's the case) is a new line that is also taken to clipboard and taken into account in the comparison.
If you select the three lines in _Notepad_ again but on "char-by-char" basis (as if you were selecting them _here_) you should get the same result.
Is that the case?

Thank you.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

> In the second case perhaps you have copied the three lines on a "line" basis in Notepad (selecting them through the lines number margin).

That is correct. 👍 
But this is how I usually select multiple lines in NPP.

Should I close this issue?
Anyway, I think it's not worth postponing ComparePlus release.

Thank you.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thanks again for the detailed explanation and for your hard work. 👍 

The current implementation is great, and closing the issue seems the right decision.

BR
