### ISSUE TITLE
Clear-compare closes original in main view

### ISSUE THREAD

**Issue by xylographe** [pnedev/compare-plugin#48]
CP 1d3e95abb30526a96dd58d3f07b9c0296201bfcc
NPP 6.9.1
Win7SP1[64]

- Open two files in main view:  (A, B)
- Clone B to sub view: (A, B | B)
- Select A in main view
- Trigger A-B compare
- Clear compare

Result: diff marks are cleared and B is closed in the main view: (A | B)
Expected: diff marks are cleared and no further action: (A B | B)

No big deal, as I would normally close B in the sub view (I can now move B to the main view instead), but I thought I should mention it anyway.

**Comment by pnedev** [comment]
I'll have a look soon, thanks for reporting.
Sounds like a N++ issue at first look but needs further investigation.

BR

**Comment by Yaron10** [comment]
Hello xylographe,

Thanks for that.

Hello Pavel,

Thank you for your work. :)

BR

**Comment by pnedev** [comment]
Hello @xylographe ,

N++ cloned file view is not correct after the "Clone" operation.
If you clone file A from main view, the cloned A file in the second view has buffer Id corresponding to the main view.

Shortly put - it is a N++ issue as I suspected.
I cannot think of a proper workaround for this - N++ needs to be fixed in this case.
It was FYI, Thanks.

BR

**Comment by xylographe** [comment]
Thank you, Pavel, for looking into and explaining this issue.
I won't put my money on a fix in NPP. :) Fortunately, there are alternatives.

**Comment by pnedev** [comment]
Hello @xylographe ,

I'll reopen the issue just to have it logged as a known problem. Thanks.

BR

**Comment by pnedev** [comment]
Hello,

Now that we have "Known issues" list I'll close this one.
Thanks.

BR

**Comment by Yaron10** [comment]
Hello,

As of now - the file is closed on Compare (i.e. before Clear).

BR
