### ISSUE TITLE
Wrong behavior after "Move to Other View"

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#60]
Hello Pavel,

This issue started before the last refactoring.

STR:
Open three files in Single-View mode.
Compare.
Activate the file at top.
Move to Other View.

Result:
The file at bottom is moved to top.

Thank you.
BR

**Comment by pnedev** [comment]
Hello Yaron,

Why would it be wrong behavior?

1) A, B, C in single view.
2) Compare A and B, B is moved to other view.
3) Focus on A and move it to other view.

At that point A and B compare is cleared and B is restored to its original view.
Seems perfectly OK to me.
Thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

> At that point A and B compare is cleared and B is restored to its original view.

This is the implementation "behind the scenes".
The user would expect the behavior to resemble "Move to Other View" in the same layout without Compare.

Thank you.
BR

**Comment by Yaron10** [comment]
Hello Pavel,

After some more thinking:
The desired result in this case can be debated.
On the one hand you don't have an explicit "Clear" but rather an explicit "Move to Other View".
On the other hand "Move to Other View" implies "Clear". 

I still tend to prefer the behavior resembling "Move to Other View" in the same layout without Compare.
What do you think? Would it require some major rework?

Thank you.
BR

**Comment by pnedev** [comment]
Hello Yaron,

The logical thing for me is to clear compare and restore the original position as it is now (that's why I've implemented it this way :)
But still, the other behavior also has its good sides. Perhaps if the user doesn't explicitly clear compare but moves directly one of the compared files he would really expect them to remain in their current positions.

@xylographe, what do you think on this?

> Would it require some major rework?

It looks easy to implement, no problem.

BR

**Comment by xylographe** [comment]
Hello Pavel,

Because CP has moved file B to the other view, CP *must* restore the original position (move B back to the main view) when the Compare is cleared. It doesn't matter if the "Clear Compare" is implicit or explicit. Any user initiated action that clears the Compare (like moving one of the involved files to another NPP instance, or closing one of the involved files) should be handled as if an explicit "Clear Compare" had been invoked before invoking that action.

Of course, in this case, there is always the (theoretical) possibility to move back B when the user moves A to the other view, and not clear the current Compare, effectively toggling compare layout (swapping "Old file position" for this particular Compare). \[BTW This is not a request for implementation, but it is tempting… :) ]

**Comment by pnedev** [comment]
Hello @xylographe ,

Thanks for the opinion. I also think this is the right behavior - nothing implicit or hidden.

> swapping "Old file position" for this particular Compare

Thanks for bringing this forward.
I was thinking of implementing a dedicated plugin command for that purpose at some point (a "Swap Active Compare" command). I'm not sure it's worth the extra work though.
Do you guys find this justified enough?

BR

**Comment by xylographe** [comment]
I'm positive I won't be using that feature. But, if you decide to implement it, I would suggest to use the existing "Move to Other View" NPP command, rather than adding a new CP command.

What *might* be useful to me, is swapping base/focal (implies re-compare) i/o swapping position. However, as I would only use that infrequently, it isn't worth the extra work. Currently, I can achieve this type of swapping with `Alt-F`, `Alt-V`, `Alt-D`.

**Comment by pnedev** [comment]
Thanks @xylographe .

**Comment by Yaron10** [comment]
Hello gentlemen,

You are right. :+1: 
Closing a compared file is also an implicit "Clear" and the other file is restored to its original view.
Thank you.
***
> Of course, in this case, there is always the (theoretical) possibility to move back B when the user moves A to the other view, and not clear the current Compare, effectively toggling compare layout (swapping "Old file position" for this particular Compare). [BTW This is not a request for implementation, but it is tempting… :) ]

That's a nice idea. 

> I was thinking of implementing a dedicated plugin command for that purpose at some point (a "Swap Active Compare" command). I'm not sure it's worth the extra work though.

Actually this can be achieved with "Set First".
Currently if you try to set a compared file as First, the operation is ignored.
But you can allow "Set First" to the current **"second"** file (according to the First setting) and swap Old and New in the next Compare.

If the user "Set First" to the currently first file: "File X is already First - operation ignored".

I'm not sure it's worth the extra work.

Best regards.

**Comment by pnedev** [comment]
Hello Yaron,

I'm glad we agreed on this, thanks.

> Actually this can be achieved with "Set First".

Interesting idea but the swap functionality is not worth the extra effort.
Thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you.

BR
