### ISSUE TITLE
[Question] Move "Display Navigation Bar" to Settings Dialog

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#62]
Hello Pavel,

I don't use the NavBar. Is it a good idea?

Thank you.
BR

**Comment by pnedev** [comment]
Hello Yaron,

I think it is better to leave it in the menu because usually one needs to quickly switch on the NavBar to get a glimpse on the differences positions (sort of a differences map).
It would even be good to make a toolbar icon for this. I may implement it at some point but I haven't decided yet.

Thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you. A good answer. :)

BR
