### ISSUE TITLE
Clear Set First

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#69]
Hello Pavel,

STR:
Open three files.
Compare.
Switch to the non-compared file.
Set First.
Switch back to the compared files.
Clear Active Compare.

Result:
Set First is cleared as well.

Is this the expected behavior?

*

This leads me to a broader question:
If you Set First and switch to another tab, should "Clear **Active** Compare" be enabled and clear First?
I assume you consider switching to another tab a direct continuation of Set First. Still, it's worth some thinking.

Thank you.
BR

**Comment by pnedev** [comment]
Hello Yaron,

Yes, this was my intention when I designed it - it is the expected behavior.

As I imagine it (and it should be now) when you "Set first" all clear commands are active and no matter if you change files those remain active so you can revert "Set first" operation.

Also if you "Set first" then switch to an active compare and do "Clear Active Compare" both the active compare is cleared and the first set file is unset.

These both are because there is no dedicated "Unset first" command.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thanks for the explanation.
And many thanks again for this great feature.

BR
