### ISSUE TITLE
Avoid cluttering NPP's "Recent Files" list

### ISSUE THREAD

**Issue by xylographe** [pnedev/compare-plugin#76]
NPP adds the temporary files created by "Diff since Last Save", "SVN diff", and "Git diff" to its "Recent Files" list. But these temporary files, not being regular files, do not belong in that list. if possible, NPP should be instructed to _not_ add these temporary files to "Recent Files". Or, alternatively, if possible, CP could remove the undesired entries.

**Comment by pnedev** [comment]
Hello @xylographe ,

I'll check this, thanks for reporting.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you very much for looking into this.

If and when you try solving the similar problem we have in every Single-View Compare as well, please check if the file is indeed in the Recent list.
I've modified NPP code and the file (not the temp) is not added to that list (https://github.com/pnedev/compare-plugin/issues/19).

Thanks again.
BR

**Comment by pnedev** [comment]
Hello Yaron,

I'll check that but I cannot promise anything.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Sure. :)

Thank you.
BR

**Comment by pnedev** [comment]
Hi all,

FYI - I just filed this N++ ticket:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/2277

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you for opening that issue.
Someone out there seems to take your requests seriously. :)

Fixing that issue still wouldn't solve the temp file problem, correct? 

BR

**Comment by pnedev** [comment]
Hello Yaron,

> Fixing that issue still wouldn't solve the temp file problem, correct?

Yes, that's true.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

In case someone is going to work on that issue:
Wouldn't it be good to add a comment asking NPP to provide a way to close a file without adding it to the Recent List?

Thank you.
BR

**Comment by pnedev** [comment]
Hello Yaron,

That's not a good idea because it is a different request that will only clutter the main one.
It's better to have a separate ticket for each request. This keeps things clear and concise and helps the developers working on the issues.
Besides the ticket I've created is more of a bug while the other one is a feature request.

Thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

You're right. :)

Thank you.
BR

**Comment by Yaron10** [comment]
Hello Pavel,

Moving
```
::SetFileAttributes(name, FILE_ATTRIBUTE_NORMAL);
::DeleteFile(name);
```
to `:onBeforeClose()`
```
void ComparedFile::onBeforeClose() const
{
	activateBufferID(buffId);

	const int view = getCurrentViewId();
	clearWindow(view);
	setArrowMark(-1);

	if (isTemp)
	{
		CallScintilla(view, SCI_SETSAVEPOINT, 0, 0);
		::SetFileAttributes(name, FILE_ATTRIBUTE_NORMAL);
		::DeleteFile(name);
	}
}
```
solves the issue: the file is not added to the Recent Files list.

What do you think?

Thank you.
BR

**Comment by pnedev** [comment]
Hello Yaron,

I'll check it, thank you.

BR

**Comment by Yaron10** [comment]
:+1:

**Comment by pnedev** [comment]
Hello Yaron,

That's a brilliant idea indeed, good job! A very clever work-around for the Recent list problem. :+1: 

I expected problems in doing that because if the file is deleted **outside** Notepad++ it will open a pop-up window asking if the user wishes to keep the file in the editor but your change doesn't really trigger that. Great!

I have made a **[patch](https://github.com/pnedev/compare-plugin/commit/71df8a800317b3814335500ff1e9fdfee1dc1b8c)** with your change.
**[Here](https://ci.appveyor.com/api/buildjobs/73prt74hepv6f3a9/artifacts/ComparePlugin.dll)** is the corresponding x86 binary (but the v140_xp version as @chcg suggested).

Thank you for closing this issue. :+1: 

BR

**Comment by Yaron10** [comment]
Hello Pavel,

I'm glad it works and thank you for the kind words. :)

> I expected problems in doing that because if the file is deleted outside Notepad++ it will open a pop-up window asking if the user wishes to keep the file in the editor but your change doesn't really trigger that. 

I suppose that if a file is deleted outside Notepad++ and *immediately closed*, that message won't show up.

Thank you for your great work. I appreciate it.
BR
