### ISSUE TITLE
compare.exe failed to call notepad++ by relative path

### ISSUE THREAD

**Issue by lvanderwall** [pnedev/compare-plugin#91]
**Version:** [1.5.6.7](https://notepad-plus-plus.org/community/topic/11116/compare-plugin/11)

**Error:** _compare.exe_ failed to find _notepad++.exe_ by relative path (_..\\..\notepad++.exe_)

**Description:** I tried it on a USB-Stick connected to a Win7-computer with a standard portable install without registry-entries using default directories (_compare.exe_ was installed to _notepad++\plugins\ComparePlugin_). I checked that _notepad++exe_ existed in the right folder, but the error remained.

P.S.: I assumed this would be the right place for this bug report as Yaron [pointed to it](https://notepad-plus-plus.org/community/topic/11116/compare-plugin/11). If not please accept my apologies and delete this issue!

**Comment by pnedev** [comment]
Hello @lvanderwall ,

No problem about the bug report. You can either place it here or on the official page https://github.com/jsleroy/compare-plugin.

I've made a lot of changes to Compare plugin since v.1.5.6.7 as it had a lot of issues.
However I decided to drop support of the external launcher (that is _compare.exe_) so I cannot help you with that.
Most probably the launcher relies on the N++ registry entry to locate the _notepad.exe_ and thus it fails to find it if it is the portable version.

BR
